### ISSUE TITLE
The Editor is scrolling to the top after insert Image by url , and another problem

### ISSUE THREAD

**Issue by qkraudghgh** [froala/angular-froala#100]
Hi. I have some problem

**problem**

1. The Editor is scrolling to the top after `insert Image` by url
2. When i use `insert Image button` ( i think, use this button three or four times )
    this button is froze up suddenly

**using version**

1. angular-froala `v2.2.3`
2. angular `v1.4.3`

Please I want know whether this problem is editor's problem

Thanks,
myoungho.Pak

**Comment by stefanneculai** [comment]
Are you able to replicate this on [our website](froala.com/wysiwyg-editor)?

**Comment by qkraudghgh** [comment]
sure but i don't access your link.
I see 404 error...
https://github.com/froala/angular-froala/issues/froala.com/wysiwyg-editor
this link that right?

**Comment by stefanneculai** [comment]
It should be https://www.froala.com/wysiwyg-editor.

**Comment by stefanneculai** [comment]
Closing this due to lack of response.
