### ISSUE TITLE
use angular binding inside editor view

### ISSUE THREAD

**Issue by RizwanAslam** [froala/angular-froala#101]
Hi
I want to use angular binding inside the editor view to dynamically update some data when it is updated from outside but when i use some angular directive inside html view it will trim it and if i use angular curly braces it will show them directly into view without evaluating them. Is this possible do such a binding inside froala editor.

**Comment by stefanneculai** [comment]
I would say that it is not possible to have direct binding in the editor view. The editor is inserting the HTML as it is, without evaluating it as Angular does. What you could do is to evaluate the HTML in Angular before inserting it into the editor and then insert in the editor the built HTML.

@cgallarno Do you have any suggestions about such an use case?

**Comment by cgallarno** [comment]
Hi,
We commonly insert directives and curly braces in the editor to be
evaluated outside of the editor. It's currently is not possible to have
angular bindings inside of the editor and I can't think of a good reason
to. We render the content inside a div where angular does run and ngHide
that and ngShow the editor when the content is being edited. As for the
editor stripping out your directives you probably need to add them to
allowedHtml or allowedAttributes additionally if they are elements with no
content, then you need to add them to allowed empty tags.

**Comment by RizwanAslam** [comment]
Hi ... Thanks for the support.
In my case i was trying to bind some data to the template generated from froala editor so that it will be updated when the data source is updated ....... it is possible by ng-bind-html angular directive or for me when i insert html into view from controller i  can use 
$compile(
        '<h1 ng-hide="true">Hi</h1>'
        )($scope)
to add angular binding .......
Now if it is not possible to make it possible for angular to bind its data in froala view then every time the data source is updated i have to recompile and reinsert html into froala view..... which means i have to do all the angular stuff my self to make it possible..

**Comment by cgallarno** [comment]
Correct, ng-bind-html and froala-view will not compile into angular for security reasons.

For when we want to render html for angular to use we created this simple directive that you can use.
```js
angular.module('app')
	.directive('compileHtml', [
		'$compile',
		function($compile) {
			return {
				restrict: 'A',
				link: function(scope, element, attrs) {
					scope.$watch(attrs.compileHtml, function(newValue, oldValue) {
						element.html(newValue);
						$compile(element.contents())(scope);
					});
				}
			};
		}
	]);
```

Which can be used like this:

```html
<div compile-html="myModel"></div>
```

**Comment by RizwanAslam** [comment]
great ..... Thanks :+1:
