### ISSUE TITLE
Insert html templates to froala editor

### ISSUE THREAD

**Issue by iloverails** [froala/angular-froala#102]
Hi guys, I have an interesting questions about inserting custom html template to froala editor. For example when I past  
`<a href=\"{{viewed_property | propertyUrl | loginUrl(client.email)}}\" target=\"_blank\">  <img src=\"{{viewed_property | propertyImageUrl}}\" width=\"150\" height=\"100\" alt=\"{{ viewed_property.address }}\"/></a>
`
as html to froala it saves as encoded text:
`<a href="%5C%22%7B%7Bviewed_property" target='\"_blank\"'><img src="\&quot;{{viewed_property" height="\&quot;100\&quot;" alt="\&quot;{{" class="fr-dii fr-draggable" style="width: 0px;"></a>`
Is this possible to save html as I inserted without encoding?

**Comment by stefanneculai** [comment]
See the [entities option](https://www.froala.com/wysiwyg-editor/docs/options#entities)

**Comment by iloverails** [comment]
Hmm.. Not sure how it works.. I included plugin and set option entities: '', but is the same result... Could you provide example of this option please

**Comment by stefanneculai** [comment]
`href` and `src` attributes are sanitizied to prevent XSS attacks. If you want to allow curly brackets inside that you should change the sanitizeURL method.

**Comment by iloverails** [comment]
How can I change it via angular-froala directive?

**Comment by stefanneculai** [comment]
You would have to make this changes in the editor unminified JS.

**Comment by iloverails** [comment]
eh, could you also give the cue for what the value shall I change this method?

**Comment by stefanneculai** [comment]
@iloverails we maintain this repo for bug tracking, not tech support. For tech support, please [contact us](https://www.froala.com/wysiwyg-editor/contact) via our website. Thank you.

**Comment by iloverails** [comment]
ah ok, sorry

**Comment by cgallarno** [comment]
@iloverails Have you also tried using the ng-href and ng-src attributes? From my testing those don't get sanitized and still work as expected. 
```
<a ng-href="{{ myLink }}" target="_blank">A Link</a>
```

**Comment by iloverails** [comment]
@cgallarno yep, it's good idea if you will use it in angular app, but I'll use html without angular

**Comment by cgallarno** [comment]
What about using angular's `$compile` service to compile the code with angular when you're done editing and then save the result? https://docs.angularjs.org/api/ng/service/$compile
