### ISSUE TITLE
events: 'froalaEditor.commands.before' is not firing untill editor is selected with a mouse click

### ISSUE THREAD

**Issue by Mekimuraosu** [froala/angular-froala#105]
Hey

I have an editor that is using the html code view, and from what I could see on previous issues, it is with good reason that the codeView is not updating the model constantly.

I have a modal that the editor is shown inside, and it saves the model to a database when a button is clicked, but when saved inside the codeView it saves nothing unless the user clicks back to the text view.

So to prevent errors with unsaved data, I wanted to disable the save button (using `ng-disabled` with a value on the scope in the controller) and i'm using this code bit in the `$scope.froalaOptions` which is passed to the directive.

```
events: {
            'froalaEditor.commands.before': function (e, editor, cmd) {

                if (cmd === 'html')
                {
                    $scope.ToggleSaveable();
                }
```

the function `ToggleSaveable` works instantly if I bind it to an `ng-click` on a seperate button, and works nicely with `froalaEditor.initialized`, but for some reason using it this way will only disable the save button once the text editor is clicked, but because the editor gets focus when the codeView button is clicked, then it's possible to past text into the editor that will then not be saved and the save button is still not disabled.

When going back to the normal editor view, it still has the save button disabled but seems to update the scope value after a few seconds and the save button is automatically enabled, this however never happens while on the codeView

Is there a better way to call disable the button when the codeView is selected, or even a better way to make sure that the model is correctly updated when saved while the codeView is showing?

**Comment by cgallarno** [comment]
Hey @Mekimuraosu, I ran into this same issue of 'saving' the content of the model but from the html mode the model wasn't updated. So what I did was if the code view was visible, (You could set a boolean in your 'html.before' method), I would toggle the codeView to close it which would update the model. https://www.froala.com/wysiwyg-editor/docs/methods#codeView.toggle

**Comment by Mekimuraosu** [comment]
Thank you, this worked nicely for me!
