### ISSUE TITLE
flashy behaviour

### ISSUE THREAD

**Issue by samvloeberghs** [froala/angular-froala#107]
When scrolling on a page that has the froala editor, it has some flashy behaviour..
Stopping on some points even keeps the flashy state

<img width="916" alt="screen shot 2016-05-09 at 20 01 33" src="https://cloud.githubusercontent.com/assets/231618/15122780/de006fa2-1620-11e6-8483-ede721709573.png">
<img width="946" alt="screen shot 2016-05-09 at 20 01 37" src="https://cloud.githubusercontent.com/assets/231618/15122781/de09f3f6-1620-11e6-9227-6c10f5a5e12c.png">

**Comment by stefanneculai** [comment]
Could you please check with V2.3.0 and let us know if you still have the problem? If the problem is still there, please make a jsFiddle for it.

**Comment by samvloeberghs** [comment]
it seems to be fixed with this version :) supergreat! 👍
