### ISSUE TITLE
Froala dependency for angular-froala

### ISSUE THREAD

**Issue by igorbarbashin** [froala/angular-froala#11]
Is there a reason why dependency for angular-froala is named FroalaWysiwygEditor?
`"FroalaWysiwygEditor": "1.2.4",`

Do I need to install `froala` as well or just `angular-froala` is enough, while it's downloading same froala under different name?

**Comment by stefanneculai** [comment]
`froala-angular` is using the bower package `FroalaWysiwygEditor` which contains the JS files and CSS for the Froala editor. You should install `angular-froala` if you want to use the Angular package.
