### ISSUE TITLE
Froala issue with undefined content

### ISSUE THREAD

**Issue by ivassiliev** [froala/angular-froala#110]
Hi,

When given undefined content, Froala throws an error in 2.3.0

Plunker: http://plnkr.co/edit/GOzUPT6s9QFL7MXGYbc3

Please see the console output.

Thanks,

Ilia

**Comment by stefanneculai** [comment]
That has been fixed after release 2.3.0: b083a1992a4f424582a7c482de966c542f1b9ca6.
