### ISSUE TITLE
When i save text, sometimes all <img> tag disappear

### ISSUE THREAD

**Issue by qkraudghgh** [froala/angular-froala#115]
Hi !
I have some Issue

### previously
```
"angular-froala": "~2.0.5"
"angular": "~1.4.3"
```
> I use it.

### Issue
 When i save some contents(img, text) using froala editor, sometimes all `img tags` disappeared.
 I don't know why , I tried many attemps but it's randomly occured

Disappear `image tags` and some `br tags`

----

I really love this library, and well used.

Thank you!

**Comment by stefanneculai** [comment]
@qkraudghgh first of all please use the latest V2.3.4 version. You might have a sanitizier on server side that removes them.
