### ISSUE TITLE
With froala editor ng-embed showing error (Important)

### ISSUE THREAD

**Issue by Rahul-Giri** [froala/angular-froala#118]
Hi,

I'm using froala editor to insert some wisywig functionality to my post. i'm also using ng-embed on it. like this.

<span froala-view="post.body | embed"></span>
then it's showing this error :disappointed:

Error: [$sce:itype] Attempted to trust a non-string value in a content requiring a string: Context: html
[error link](https://docs.angularjs.org/error/$sce/itype?p0=html)

I checked angular-froala source code. and there is something which need to modify in order to that. i could be wrong. but this is the problem with angular-froala somewhere.

this is the lib filter i'm using [ng-embed link](https://github.com/ritz078/ng-embed) 

What i should do now ?

**Comment by stefanneculai** [comment]
@Rahul-Giri the content of the editor should be a HTML string, it cannot be dynamic.
