### ISSUE TITLE
Using `froala` inside a custom directive ignores options

### ISSUE THREAD

**Issue by stevie-p** [froala/angular-froala#119]
Hi

I'm in the process of checking out whether (angular-)Froala can do what I need it to.

The `froala` directive works well on its own, but if it is used in a custom directive, it does not pick up any passed in options (such as `toolbarInline`).
[See this Plunk](http://plnkr.co/edit/szumjuzYHLByRxjRf3gI?p=preview)

Is this a bug, am I doing something wrong, or does Froala not support this use-case?

Thanks

**Comment by jwhitmarsh** [comment]
@stevie-p did you get anywhere with this? I'm experiencing the same issue.

**Comment by peterjkirby** [comment]
+1

**Comment by stefanneculai** [comment]
This doesn't appear to be a problem with the Froala directive. It looks like Angular is calling the link method from the inner directive before setting the scope in the outer one. See the logs from the console: http://plnkr.co/edit/1gX3QCAMVluj9NiNMg34?p=preview.
