### ISSUE TITLE
Bootstrap modal and textarea: could not enter any text

### ISSUE THREAD

**Issue by kotmatpockuh** [froala/angular-froala#12]
Hello. I have one trouble: when i use this textarea form with bootstrap modal window i could not change any link or text, i mean:

`https://dl.dropboxusercontent.com/u/59666091/Screenshot_1.png`

`https://dl.dropboxusercontent.com/u/59666091/Screenshot_2.png`

how could i fix this?

**Comment by kotmatpockuh** [comment]
is similar to https://github.com/froala/wysiwyg-editor/issues/131

**Comment by stefanneculai** [comment]
Please make a jsFiddle.

**Comment by kotmatpockuh** [comment]
fixed with removing tabindex="-1"
