### ISSUE TITLE
Update froala-sanitize.js to mirror up to date ng-sanitize version

### ISSUE THREAD

**Issue by ghost** [froala/angular-froala#122]
Hello,
we are using this amazing editor.  We are using also froala-sanitize.js which we have noticed is based on 1.3.0 angular. It would be great to keep up to date with the latest angular-sanitize version. We have noticed there are some parts of code different - for example linky filter in 1.5.8 angular has more arguments than it had in 1.3.0 and some more functionality changes. (www. links suport, ...)

Thanks in advance

**Comment by stefanneculai** [comment]
@TheNightmareDev could you please make a PR? Thank you.

**Comment by stefanneculai** [comment]
@cgallarno all that should be done for this is to copy https://github.com/angular/angular.js/blob/master/src/ngSanitize/sanitize.js to froala-sanitize.js?

**Comment by s00141425** [comment]
I would like to appy 'angular-froala' with webpack 2.0.
but it looks like it doesn't work with commonjs (eg componentjs, Webpack, Browserify).

doesn't the angular-froala support requireJS yet?

angular.module('myModule', [require('froala'));
