### ISSUE TITLE
set withCredentials to false

### ISSUE THREAD

**Issue by zockfoul** [froala/angular-froala#126]
Hi, everyone. I'm getting this error :

<img width="1276" alt="captura de pantalla 2016-10-04 a las 10 58 34 p m" src="https://cloud.githubusercontent.com/assets/5187386/19098664/9f7f4490-8a85-11e6-83d0-b4c9482f8fe9.png">

I'm trying to find a way to set the option credentials to false but I failed to find anything in the documentation. Try going to do so in the settings but it has not worked:

.value('froalaConfig', {
        withCredentials: false,
        toolbarInline: false,
        language: 'es',
        imageUploadURL: 'http://evaluaciones.app/api/v1/file/image/upload',
        fileUploadURL: 'http://evaluaciones.app/api/v1/file/pdf/upload'
});

Thanks greetings.

**Comment by stefanneculai** [comment]
Starting with V2.3.5, there is going to be an option called: `requestWithCredentials` to disable it. In the meanwhile you can use the `requestWithCORS` to disable this.
