### ISSUE TITLE
requestWithCredentials not using origin header

### ISSUE THREAD

**Issue by nick-berry** [froala/angular-froala#129]
Not sure if I'm misunderstanding how the "requestWithCredentials" option works but I'm having a bit of trouble. When uploading an image, the initial POST sends my cookie and an origin header. The subsequent request to get the image data to insert into the WYSIWYG contains the cookie, but not the origin header. The authorization built into the backend I am using requires the origin header for authorization. Attempted to set it via the "requestHeaders" option, but since it is an unsafe header I am unable to monkeypatch. Are there any known workarounds for such a scenario? 
Thanks.

**Comment by nick-berry** [comment]
Looks like the second request is made by the browser (in the image src attribute) and isn't made by a jQuery XMLHttpRequest in the tool like I thought. Closing this one.

**Comment by elhendawy** [comment]
Hi,
I am facing the same issue, did you come up with a workaround.
Thanks
