### ISSUE TITLE
ImageUpload with headers

### ISSUE THREAD

**Issue by kotmatpockuh** [froala/angular-froala#13]
https://editor.froala.com/server-integrations/php-image-upload

Hello. Could you please provide information:

how could i send authToken and some other headers in imageUpload code?

```
 $(function() {
    $('.selector').editable({
      // Set the image upload URL.
      imageUploadURL: '/upload_image.php',

      imageUploadParams: {id: "my_editor"}
    })
 });
```

params i see, but how to be with custom headers like authToken etc?

**Comment by pietrovismara** [comment]
+1 Is it possible? I can't find any explanation about it.
