### ISSUE TITLE
Adding a colored background to large text ends up giving it a sort of thick underline instead

### ISSUE THREAD

**Issue by ClaytonKinder** [froala/angular-froala#130]
![image](https://cloud.githubusercontent.com/assets/12376135/20728010/bfb129be-b649-11e6-8972-c22bf2084485.png)

If you add a background to large text, it appears like the top text in the image. If you add the background first and then enlarge it, it appears normally.

**Comment by stefanneculai** [comment]
I am closing this in favor of froala/wysiwyg-editor#1715.
