### ISSUE TITLE
element.froalaEditor is not a function

### ISSUE THREAD

**Issue by bernardocs** [froala/angular-froala#134]
Hey guys... 😄 

I've searched in every corner for a solution for the `element.froalaEditor is not a function` problem... found a bunch of similar situations but most of then did not included webpack.

For context, we're using Angular + Webpack 2 with Babel.
We used npm to install the package. Should we, I don't know, somehow include the `froala-editor` package before everything or something? Because that's the general solution that everyone gives when it comes to this error.

I'm getting this error while trying to use the directive and still didn't figured it out how to solve this _without having to add a bunch of script tags, importing everything_ (that's why webpack is in the project). 😖 

Any ideas, guys?! 🤔

**Comment by stefanneculai** [comment]
@bernardocs most likely you are not including the editor JS files.
