### ISSUE TITLE
Unable to bind html data to froala ng-modal

### ISSUE THREAD

**Issue by summit2020** [froala/angular-froala#139]
Instead of displaying html on editor, i get html as plain text on it. 

What's the problem here ?
 
![capture](https://cloud.githubusercontent.com/assets/8147758/25869850/8ec4911a-351f-11e7-8c5a-51fa73e534fb.PNG)

Remark: Angular Js Version - 1.0.8

**Comment by stefanneculai** [comment]
It looks like the HTML you're putting there is not being marked as safe and that's why it gets escaped.
