### ISSUE TITLE
Append image/link popup to scrollable container

### ISSUE THREAD

**Issue by kotmatpockuh** [froala/angular-froala#14]
For example: in config i try to code, that all popup's are attached to `.froala-wrapper.f-basic`, but then i didn't see any popup, even if i try to change z-index etc...

so: i append such code in config:

    editorClass: "my-custom-class",
    scrollableContainer: '.my-custom-class'

and any popup is displayed (case when froala editor is in bootstrap modal with fixed editor height)

you could try it here https://editor.froala.com/ if you set editor height to fixable, and uploading very tall image: with image popup position is something wrong. Screenshot: http://prntscr.com/6krb77

Take a look at this. Thank you.

**Comment by kotmatpockuh** [comment]
also, could you please update bower? 
`"dependencies": {
    "FroalaWysiwygEditor": "1.2.6",
    "angular": "~1.2.22"
  }`

to "FroalaWysiwygEditor": "1.2.7" ?

**Comment by kotmatpockuh** [comment]
also JFYI: wysiwyg must sanitize { } values to... No symbols { and } stayed in code.

**Comment by stefanneculai** [comment]
Please open an issue on https://github.com/froala/wysiwyg-editor regarding your first comment.

Regarding your 2nd comment, the version 1.2.7 is not released officially yet. The dependencies will be updated just when the new version is officially released.

@cgallarno could you please advise about the latest comment?
