### ISSUE TITLE
How to change language

### ISSUE THREAD

**Issue by clluiz** [froala/angular-froala#142]
There is a option to chang de language?

**Comment by stefanneculai** [comment]
@clluiz yes, you should set the language via the language option:
https://github.com/froala/angular-froala#options
https://www.froala.com/wysiwyg-editor/languages

**Comment by Khrystyna** [comment]
@stefanneculai  I am passing the language code as an option, but it still doesn't work. Can it be that locale files are not included into build version?

**Comment by stefanneculai** [comment]
@Khrystyna you should include the language files separately, they are not included in the package by default.

**Comment by fiatkongen** [comment]
Has anyone made this work? I have included the danish language file from https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.9.5/js/languages/da.js

And added to options: language: 'da'

But it still does not work

**Comment by langereissilvio** [comment]
@fiatkongen Not sure if you solved it or not, but I managed to get it working by importing the file directly into your component: ` import 'node_modules/froala-editor/js/languages/nl.js';`

**Comment by C0rporeus** [comment]
> @fiatkongen No estoy seguro si lo resolvió o no, pero logré hacerlo funcionar importando el archivo directamente a su componente:` import 'node_modules/froala-editor/js/languages/nl.js';`

me too
