### ISSUE TITLE
Different result when adding a <br /> on windows and osx

### ISSUE THREAD

**Issue by RHinderiks** [froala/angular-froala#145]
##### Expected behavior.
When adding a br tag through code i expect this to add an empty row on both windows and MacOS

##### Actual behavior.
On windows it seems to wrap the br tag in a p tag and also it seems to render it differently.

##### Steps to reproduce the problem.
Add a piece of text, than press a button or something to programmatically add an br tag and a piece of text to the editor. This will result in the attached files.

![macos_sierra](https://user-images.githubusercontent.com/26223525/28008235-02411192-6557-11e7-9622-504d973120c3.png)
![windows_10](https://user-images.githubusercontent.com/26223525/28008236-02434b06-6557-11e7-8486-2c590de72ff6.png)

##### OS.
MacOS Sierra (latest)
Windows 10 (latest)

##### Browser.
Chrome (latest)
Firefox (Latest)

**Comment by stefanneculai** [comment]
@RHinderiks could you please let us know the exact steps to reproduce this? Also, are you able to reproduce it here: https://www.froala.com/wysiwyg-editor/examples/enter?

**Comment by RHinderiks** [comment]
I am not able to reproduce it since that example doesn't use any angular. I'm not quite sure how to achieve the same effect (Adding text to an editor). Because of the 2 way binding in angular its quite simple.

The exact steps are as follows:
1. type a piece of text in the editor
2. Somehow add a <br /> and a bit of text to the already present text. (in our system this happens when i open the message again)

**Comment by stefanneculai** [comment]
We couldn't reproduce it on a blank application. @RHinderiks could you make a Plunker for it?

**Comment by RHinderiks** [comment]
@stefanneculai i'll see if i can reproduce it. I am quite busy at the moment so it may take a while.

**Comment by stefanneculai** [comment]
OK. Thanks.

**Comment by samhsuqld** [comment]
I was experiencing a similar issue: if you're using the default `enter` setting, the HTML you add must start and end with a paragraph tag, or Froala will wrap the HTML you add in a paragraph tag automatically.

You can reproduce this without using Angular by using the code-view plugin. Hope this helps.

**Comment by stefanneculai** [comment]
@samhsuqld could you please send the HTML you're using for this?

**Comment by samhsuqld** [comment]
See this [plunker](http://plnkr.co/edit/Ebt2o0ch6HNbJSOLLRmN?p=preview) for a basic reproduction.

**Comment by stefanneculai** [comment]
@samhsuqld this is the editor default behavior. When using the default options, new lines are automatically being wrapper with a P tag. If you want to disable it, then you should change `enter` option to `$.FroalaEditor.ENTER_BR`. https://www.froala.com/wysiwyg-editor/examples/enter
