### ISSUE TITLE
Can you please create 2.6.2 release , Thank you!

### ISSUE THREAD

**Issue by klipmaniac** [froala/angular-froala#146]

**Comment by stefanneculai** [comment]
@klipmaniac it is no longer necessary to make a separate release here when the editor is updated. You can update separately the `froala-editor` dependency by running: `npm update froala-editor`.

**Comment by jose-douglas-ramirez** [comment]
Hi @stefanneculai 

The lastest release of the editor is:
![image](https://user-images.githubusercontent.com/22900723/28070315-10c1f84c-6612-11e7-9796-a452249bce8a.png)

An the lastest release of the directive is:
![image](https://user-images.githubusercontent.com/22900723/28070362-3b9c5314-6612-11e7-862f-8927b1c6995a.png)

Our question is can we use the versiion 2.61 of the directive with the version 2.62 of the editor? Thanks!

**Comment by stefanneculai** [comment]
Yes, that is right.

**Comment by jose-douglas-ramirez** [comment]
ok, this is our bower json

![image](https://user-images.githubusercontent.com/22900723/28070885-069864b2-6614-11e7-8ea8-c006dde0acdd.png)

How we could indicate the version of the editor? Thanks in advance

**Comment by stefanneculai** [comment]
The `froala-editor` dependency for `angular-froala` plugin is set here: https://github.com/froala/angular-froala/blob/master/bower.json#L33. If you're using bower, all you should do is to run `bower install froala-wysiwyg-editor`. This should install the version 2.6.2.

**Comment by jose-douglas-ramirez** [comment]
thanks @stefanneculai only for confirm our bower json now looks  like, is this correct?:

![image](https://user-images.githubusercontent.com/22900723/28071449-93f97c28-6615-11e7-838c-0c3389444c46.png)

**Comment by stefanneculai** [comment]
Yes, that is correct. 👍

**Comment by klipmaniac** [comment]
Stefan thank you for your help on this, I guess I didnt realize till now that you work for froala, I emailed you about the Edge bug when pasting a table in the editor via Edge browser I just get the content not the actual table.. I updated now to 2.6.2, you sent me a link to 2.6.2 via email of this fix? Im not sure how to fix this issue, I update to 2.6.2 and still have it.

Thank you.

**Comment by klipmaniac** [comment]
I mean if you go to your editor on your page (https://www.froala.com/wysiwyg-editor/) and copy paste from word using the Edge browser you will see the same issue we are seeing...

**Comment by klipmaniac** [comment]
plunker not working either with word copy paste via Edge ....
https://plnkr.co/edit/WxAw15Dt6xcwSYH8ixke?p=preview

**Comment by stefanneculai** [comment]
@klipmaniac the fix is in V2.6.3 which is still under development and is not released yet. To try it, you could do the following: `bower install --save froala-wysiwyg-editor#master`. This should use the master branch from Github which is not released yet.
