### ISSUE TITLE
Cannot read property 'POPUP_TEMPLATES' of undefined

### ISSUE THREAD

**Issue by albertosubero** [froala/angular-froala#148]
image.min.js:7 Uncaught TypeError: Cannot read property 'POPUP_TEMPLATES' of undefined
    at image.min.js:7
    at image.min.js:7
    at image.min.js:7

**Comment by stefanneculai** [comment]
@albertosubero please make sure you include the editor main JS file before the image plugin.

**Comment by Heila-Almogren** [comment]
just in case anyone goes through this, I was using it in angular and faced this issue. First second, you need to add the plugin js in the "plugins" folder in froala-editor node modules folder (`froala-editor/js/plugins/<plugin_name>.min.js`). previously i putted it in other place.

second, I removed the js reference I added previously in "scripts" tag in angular.json for image.min.js and only imported directly it in the app module:
`import 'froala-editor/js/plugins/image.min.js';`
this way the error disappeared.
