### ISSUE TITLE
ng-model keeps tags from Scayt Spellchecker

### ISSUE THREAD

**Issue by SashaMihalache** [froala/angular-froala#149]
![moraru](https://user-images.githubusercontent.com/7697631/29559450-d37bc49e-8737-11e7-9916-c25c1154ffef.jpg)

`<p fr-original-style="box-sizing: border-box; margin: 0px 0px 10.5px; font-size: 14px;" style="box-sizing: border-box; margin: 0px 0px 10.5px; font-size: 14px;"><span data-scayt-lang="en_US" data-scayt-word="Lorem" fr-original-class="scayt-misspell-word" style="box-sizing: border-box;">Lorem</span> <span data-scayt-lang="en_US" data-scayt-word="ipsum" fr-original-class="scayt-misspell-word" style="box-sizing: border-box;">ipsum</span> dolor sit <span data-scayt-lang="en_US" data-scayt-word="amet" fr-original-class="scayt-misspell-word" style="box-sizing: border-box;">amet</span>, <span data-scayt-lang="en_US" data-scayt-word="consectetur" fr-original-class="scayt-misspell-word" style="box-sizing: border-box;">consectetur</span> <span data-scayt-lang="en_US" data-scayt-word="adipiscing" fr-original-class="scayt-misspell-word" style="box-sizing: border-box;">adipiscing</span> elit.</p>`

All Scayt tags are kept on the ng-model and also if I run `$("#froala-0").froalaEditor("html.get")` this returns the same thing and it should be expected to not have any Scayt tags.

**Comment by stefanneculai** [comment]
@SashaMihalache please make sure you are using the latest editor version 2.6.5. 
https://github.com/froala/angular-froala#update-editor
