### ISSUE TITLE
editor.events.add within plugin init not working

### ISSUE THREAD

**Issue by StefanNeuser** [froala/angular-froala#151]
Hi, i'm checking out froala editor on my local machine to figure out if the editor fits in our needs.

The console.log(editor) is working but the next lines are not working
```
      // You can listen to any event from documentation.
      // editor.events.add('contentChanged', function (params) {});
```
Error in Console:
```
[Vue warn]: Error in mounted hook: "TypeError: editor.events.add is not a function"

found in

---> <Froala>
       <Root>
```

I guess this is something special within the vuejs froala plugin.

**Comment by stefanneculai** [comment]
This repo is for the Angular plugin, not for the Vue one. The Vue one is on https://github.com/froala/vue-froala-wysiwyg.
