### ISSUE TITLE
Some froala options not visible within 2 bootstrap modals

### ISSUE THREAD

**Issue by RHinderiks** [froala/angular-froala#154]
When using bootstrap 3 modal it seems to stop working when opening a modal on top of a other modal. 

Tested on MacOs with latest safari and latest chrome versions.

The following don't seem to work. color, table, hyperlink. However headers seem to be working fine

It works fine within a single modal. Example:

<img width="1049" alt="screen shot 2017-10-15 at 17 25 42" src="https://user-images.githubusercontent.com/26223525/31586176-09cfab12-b1ce-11e7-80cf-effa5fda06e6.png">
<img width="880" alt="screen shot 2017-10-15 at 17 26 05" src="https://user-images.githubusercontent.com/26223525/31586177-09e7de30-b1ce-11e7-8906-b9f03c6e80ff.png">

**Comment by RHinderiks** [comment]
The problem is a inline styling being set when the option toolbarInline is set to true, It sets a z-index 5 with inline styling. this also makes it impossible to override our selves !

**Comment by stefanneculai** [comment]
@RHinderiks when using the bootstrap modal, please make sure you set the editor zIndex option to a higher value. There is a demo here: https://github.com/froala/wysiwyg-editor/blob/master/html/3rd-party/bootstrap/modal.html.
