### ISSUE TITLE
Weird behaviour in ios 11

### ISSUE THREAD

**Issue by RHinderiks** [froala/angular-froala#155]
Using ios 11 on an ipad results in weird behaviour even on your own website mostly the inline editor demo. It loses focus after the first enter and in our own application we find that in combination with bootstrap 3 modals and the ipad in landscape mode we can press on a line but will trigger an element not even within the froala editor.

os: ios 11
position: landscape
version: froala 2.7.0
dependencies: some issues on bootstrap modals other on your own website
editor: inline

**Comment by stefanneculai** [comment]
@RHinderiks could you please provide the exact steps to reproduce the issue? Thanks.

**Comment by RHinderiks** [comment]
Turn the ipad in landscape mode, when selecting a row to type it works fine but when pressing the return key it seems to unfocus. This is on your own website.

**Comment by RHinderiks** [comment]
@stefanneculai any news on this issue ?

**Comment by stefanneculai** [comment]
@RHinderiks could you try version 2.7.5 and let us know if you still have this problem? Thank you.
