### ISSUE TITLE
Using a licenses Froala inside in Iframe in a Chrome Extension

### ISSUE THREAD

**Issue by ahmadassaf** [froala/angular-froala#158]
Hello,

We have purhcased a Business License for Froala and are using it with Angular inside of an app that is loaded within an iFrame as a Chrome Extension. My understanding is that the license is loaded and checked against domain names, however as a technical requirement the source of the chrome extension is not set to a specific domain but rather to a URI relative to the chrome extension location e.g., `chrome-extension://...`

Any ideas on how to load the license in that case ? 

Much appreciated

**Comment by stefanneculai** [comment]
@ahmadassaf please reach us via our website and our support team will assist you with it: https://www.froala.com/wysiwyg-editor/contact.
