### ISSUE TITLE
Froala Sanitize

### ISSUE THREAD

**Issue by Mr-Anonymous** [froala/angular-froala#16]
Is froala-sanitize.js the same as angular-sanitize.js ? I mean, if I've already linked my app to angular-sanitize.js, can I safely ignore adding froala-sanitize.js (or) does the editor has some dependency on froala-sanitize.js file only?

**Comment by cgallarno** [comment]
froala-sanitize.js extends angular-sanitize, so you would use froala-sanitize instead of angular-sanitize.
