### ISSUE TITLE
Display text instead of icon in custom dropdown

### ISSUE THREAD

**Issue by shahilg** [froala/angular-froala#163]
Hi,

I have added the custom dropdown to the editor and want to show the text instead of icon in the toolbar for the custom drop-down. Looking forward to it.

Thanks.

**Comment by stefanneculai** [comment]
For that please use the `html` property: https://www.froala.com/wysiwyg-editor/docs/concepts/custom/dropdown.

**Comment by shahilg** [comment]
@stefanneculai 
Thanks for your inputs. I tried that but it helps me to do the customization with HTML in the option. I just want to show the dropdown in the toolbar with text and not the icon.

**Comment by khlinkedselling** [comment]
Hi @stefanneculai can you please post your toolbar configuration here? I'm trying to display the custom drop-down text instead of the icon and can't seem to get it working.

**Comment by clovis1122** [comment]
BUMP. @stefanneculai any solution to this?

**Comment by ArmaanSinghKlair** [comment]
@stefanneculai any solution to this?
