### ISSUE TITLE
Froala, Unlicensed 

### ISSUE THREAD

**Issue by ditproz** [froala/angular-froala#166]
My company has purchased a fully fledged license, but we still get the little red block in the bottom left which says Unlicensed Froala.  Any ideas?

**Comment by ditproz** [comment]
Also, we do insert the license number into the configuration...
```
    this.froalaEditorOptions = {
      theme: 'custom',
      placeholderText: 'Write Something...',
      charCounterCount: true,
      key: 'KEY GOES HERE',
      heightMin: 300,
      heightMax: 400,
      toolbarBottom: true,
```

**Comment by stefanneculai** [comment]
@ditproz please contact us via [the support form](https://www.froala.com/wysiwyg-editor/contact) and our support team will help you with this matter. Thanks.

**Comment by ditproz** [comment]
I did contact you via the support form and never received an email back.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by stefanneculai** [comment]
@ditproz could you please let me know the ticket number you got?
