### ISSUE TITLE
Track deleted images in edit box

### ISSUE THREAD

**Issue by kotmatpockuh** [froala/angular-froala#17]
Hello.
I have one trouble and i do not have any ideas how to solve it (i checked up docs as well). 

I use delete method to delete files from the server, like:

      afterRemoveImage: function (e, editor, $img) {
         ***
      }

and now i have question: how could i delete images only after i click save button for example?

i try so:

after every image delete do not delete this image, but store url (or id of image) in some array then after click on save button delete all images from this array, but! there is one bad case - if user press ctrl-z or pressed undo button: image will return back, but it's id is stored in array to delete.

is it real with froala to handle undo event's on images?

maybe you could give some ideas...
thank you.

**Comment by stefanneculai** [comment]
You could check in the undo/redo events if the image got back in the editor and remove it from your array.

**Comment by kotmatpockuh** [comment]
Docs provide only html before and html after. You propose to compare this two values?

**Comment by stefanneculai** [comment]
You could check the content inside the editor and see if it contains any image that is in your array with deleted images. 

The purpose of this repo is not offering support. If you have a license that includes support, please contact us via http://editor.froala.com/contact. Thank you.

**Comment by kotmatpockuh** [comment]
hm, could i somehow on your page test this event?
on my app i see that it is not fired
