### ISSUE TITLE
Module 'froala' is not available!

### ISSUE THREAD

**Issue by bravility** [froala/angular-froala#177]
since I run `bower install froala-wysiwyg-editor --save`

1.Add the froala dependency to my Angular project. example:
`angular.module('myApp', ['froala'])`
2.Create a textarea with the froala directive in my view and give it a model, where myHtml is a variable on $scope.
`<textarea froala ng-model="myHtml"></textarea>`

It throw some error：

> Error: [$injector:nomod] Module 'froala' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

Did I miss some code？

**Comment by bravility** [comment]
I am sure that js has include and they in the right order。
![image](https://user-images.githubusercontent.com/6559992/39570906-616862e4-4efc-11e8-8a35-6be1d3a2b722.png)
![image](https://user-images.githubusercontent.com/6559992/39570936-739cf420-4efc-11e8-8825-40c9461011a4.png)

**Comment by mthomasson** [comment]
@bravility 
You should try to install angular-froala :)
