### ISSUE TITLE
Support AngularJS 1.7

### ISSUE THREAD

**Issue by juliancarrivick** [froala/angular-froala#178]
See breaking changes here: https://github.com/angular/angular.js/blob/master/CHANGELOG.md

Using in our own project, I've only noticed an issue with `froala-sanitize.js` using `angular.lowercase` which has been removed.

**Comment by mgalarza** [comment]
Why don't you open a pull request for this fix?

**Comment by mgalarza** [comment]
Thanks a lot

**Comment by stefanneculai** [comment]
The PR has just been merged.
