### ISSUE TITLE
Open in new tab not working

### ISSUE THREAD

**Issue by ktracey** [froala/angular-froala#180]
'Open in new tab'
Save and test the link, opens in same tab
Edit link and box is unchecked.

This appears to work with the native froala editor... but is not working within the angular component.. This is a problem in 2.8.0..Works in 2.7.6

**Comment by AshMcConnell** [comment]
We are actually seeing something slightly different.  QA are reporting it always opens in a new browser window rather than a new tab or same window

**Comment by ktracey** [comment]
That is not what we seeing.. we are seeing that the value of "open in new tab" is not being retained...and it always opens in the same window..  I just tried it again with 2.8.3
![step3](https://user-images.githubusercontent.com/13381295/42377072-bacfe1a2-80ef-11e8-81a1-74dc9ea2f823.png)
![step2](https://user-images.githubusercontent.com/13381295/42377073-bad9d5cc-80ef-11e8-974e-5241df86fd7a.png)
![step1](https://user-images.githubusercontent.com/13381295/42377074-bae3c26c-80ef-11e8-82f0-50f3da2d1fee.png)

**Comment by stefanneculai** [comment]
We just checked this in version 2.8.4 and it works without problem on https://www.froala.com/wysiwyg-editor. If you still have problem you might have a custom implementation that prevents it to work correctly.

**Comment by ktracey** [comment]
Does your example on  https://www.froala.com/wysiwyg-editor use the angular -froala?

**Comment by stefanneculai** [comment]
@ktracey the angular example doesn't make any changes on the HTML. I would recommend to check the output of the following command in the browser to see what version you're using: $.FE.VERSION.

**Comment by ktracey** [comment]
I figured it out.. We bundle all of our third party components.. and perform a minification on them.  For some reason this is causing an issue with this feature with the 2.8.x version of Froala (it was fine in the 2.7.x versions). I just wanted to document my findings in case others have the same issue
