### ISSUE TITLE
Exactly the same error than in Angular-froala-WYSIWYG html.set is not a function

### ISSUE THREAD

**Issue by mthomasson** [froala/angular-froala#181]
See
https://github.com/froala/angular-froala-wysiwyg/issues/206
We have exactly the same error in the Angular 1 version.

**Comment by mthomasson** [comment]
This commit https://github.com/mthomasson/angular-froala/commit/0930ae307322e8c276a398888c6327c094dc6723
solves it

**Comment by jacobcsmith** [comment]
We're also experiencing this issue

**Comment by petarblazevski** [comment]
@stefanneculai when you install the package with `npm` it installs the latest version `2.8.4` with the  issue fixed. But if you install the package with `bower` you are still getting `2.8.3`. Looking at the Release in GitHub, the latest release is flagged as `2.8.3`. Maybe this is the issue with `bower`?

**Comment by DallanQ** [comment]
@petarblazevski I believe the problem is bower relies upon the github "release" tags, and there isn't a release tag for 2.8.4, so we have to use the git sha instead.
