### ISSUE TITLE
Setting the key for v2.8.0 isn't working

### ISSUE THREAD

**Issue by jwhitmarsh** [froala/angular-froala#183]
I'm setting my new (longer) licence key via the "key" option: 

```
$scope.froalaTitleOptions = {
      toolbarInline: true,
      charCounterCount: false,
      enter: `span`,
      toolbarButtons: menuButtons,
      toolbarButtonsMD: menuButtons,
      toolbarButtonsSM: menuButtons,
      toolbarButtonsXS: menuButtons,
      htmlAllowedTags: ['div'],
      pluginsEnabled: [],
      key: CONFIG.FROALA_KEY
    };
```

but still seeing this:
![screen shot 2018-07-04 at 14 32 17](https://user-images.githubusercontent.com/8026009/42279890-16a7bae0-7f97-11e8-963e-8b129ed25b4e.png)

Licence's are perpetual, so it hasn't expired, so I assume it's because I'm setting it wrong - how should I be setting it?

**Comment by stefanneculai** [comment]
@jwhitmarsh the licenses are perpetual, you can use the version you purchased for the lifetime, however, the software updates are limited to one year. See more here: https://wysiwyg-editor.froala.help/hc/en-us/articles/115000396145-Are-the-licenses-one-time-payment-. 

Please read more about the expiration message here: https://wysiwyg-editor.froala.help/hc/en-us/articles/360000717489-Why-is-my-editor-license-expired-. If you still have troubles please contact support via https://www.froala.com/wysiwyg-editor/contact.
