### ISSUE TITLE
immediateAngularModelUpdate option not work.

### ISSUE THREAD

**Issue by towry** [froala/angular-froala#185]
I have to use `froalaEditor.contentChanged` event to update the model manually.

```js
scope.froalaOptions = {
	language: 'zh_cn',
	theme: 'moseeker',
	toolbarButtons: [
		"bold", "italic", "underline", "|", "insertImage"
	],
	events: {
		'froalaEditor.contentChanged': (e, editor) => {
			if (ignoreChange) {
				ignoreChange = false;
				return;
			}
                         // method to update the model.
			updateHtmlContent(editor.html.get(), true);
		}
	}
}
```

If there is an initialized value for the model, then `froalaEditor.contentChanged` event will be triggered, so I have to use `ignoreChange` to pass it.

**Comment by stefanneculai** [comment]
@towry do you think you could make a Plunker / jsFiddle to highlight this?

**Comment by stefanneculai** [comment]
Closing this due to lack of response.
