### ISSUE TITLE
Fabric js UI component importing issues

### ISSUE THREAD

**Issue by shankargurutarikere** [froala/angular-froala#186]
I have tried to use office UI component by installing them on my angular project by following the link in github

https://github.com/ngOfficeUIFabric/ng-officeuifabric

I am stuck with these errors!!!
![capture](https://user-images.githubusercontent.com/31584520/42754480-42123dc0-8912-11e8-8575-15031804ce42.PNG)

**Comment by stefanneculai** [comment]
This doesn't appear to be linked to the Froala Editor, but to the way you're loading Fabric JS.

**Comment by shankargurutarikere** [comment]
I have installed using this command

npm install ng-office-ui-fabric --save

I should have 
1)/node_modules/office-ui-fabric/fabric.min.css
2) /node_modules/office-ui-fabric/fabric.components.css"

these files in my node_modules folder,but i am not having.
![capture](https://user-images.githubusercontent.com/31584520/42795965-b398e2b8-89a4-11e8-8f50-4b288581e6d3.PNG)
