### ISSUE TITLE
When combined with template CoreUI angularjs, Froala editor display confused interface between Mobile and PC

### ISSUE THREAD

**Issue by TrietPham96** [froala/angular-froala#187]
I using froala editor for template CoreUI angularjs. Display is good but the interface of froala is the same on PC or Mobile

**Mobile**

![image](https://user-images.githubusercontent.com/29618357/43654896-034833c4-9777-11e8-836b-00768c1b0b0e.png)

**PC**

![image](https://user-images.githubusercontent.com/29618357/43654911-19a9cb14-9777-11e8-9eed-6ad8326d8467.png)

**On PC when i view elements, interface of froala becomes full**

![image](https://user-images.githubusercontent.com/29618357/43655056-b4c94f20-9777-11e8-9a95-f649872859da.png)

I hope for help, I do not know what I lack when I have followed the full steps

**Comment by stefanneculai** [comment]
Not sure where the problem might come from. Could you please check that you're setting correctly all the toolbar buttons: https://www.froala.com/wysiwyg-editor/examples/toolbar-buttons?

**Comment by TrietPham96** [comment]
I have fixed it, froala too perfect

**Comment by TrietPham96** [comment]
Very thanks, i 've fixed it
