### ISSUE TITLE
Cannot set video (youtube) default iframe width/height

### ISSUE THREAD

**Issue by martinduris** [froala/angular-froala#192]
Hi guys,
i am using angular froala editor 2.8.5 (angular 6+).
When we are adding video:

![1](https://user-images.githubusercontent.com/309316/47135640-60360f00-d2b1-11e8-8d69-b54dc5443458.png)

Froala add iframe. But **iframe has always same width 640px (constant).** Sometimes container, where you want to add conent from froala is smaller -> so to **improve user experience it would be perfect to change default width of iframe** (and also height).

It is possible to make this constant -> configuration variable ?

Thanks
Martin

**Comment by stefanneculai** [comment]
@martinduris please request it here: https://wysiwyg-editor-roadmap.froala.com. Thanks.
