### ISSUE TITLE
Regression causing model data to be discarded for initOnClick

### ISSUE THREAD

**Issue by FWennerdahl** [froala/angular-froala#193]
When binding data using ng-model in an editor instance created with `initOnClick: true`, the model data isn't bound to the editor. This causes the model data to effectively be discarded.

This was previously logged in #164 and fixed in #171, but was broken again in #181.

The current state makes it impossible to load existing data in an editor with initOnClick set to true.

Please see https://jsfiddle.net/8pfLjw7c/ for reproduction case.

**Comment by septianscp** [comment]
weewew
