### ISSUE TITLE
Clicking on ordered list items changes their numbers back to 0

### ISSUE THREAD

**Issue by phuongpt** [froala/angular-froala#194]
Hi guys,
I click around on the items while editing and.... the numbers change to 0 on each one I click on. 
I'm using angular v1 and ionic.

![screen shot 2018-11-05 at 11 53 47 am](https://user-images.githubusercontent.com/4443583/47978666-a84a9380-e0f1-11e8-8fe1-304b7c4193ca.png)
![screen shot 2018-11-05 at 11 53 28 am](https://user-images.githubusercontent.com/4443583/47978672-abde1a80-e0f1-11e8-8c68-6ad53b257561.png)

**Comment by stefanneculai** [comment]
@phuongpt most likely you have some CSS there on the page which gets into conflict with the editor and changes the list style item.
