### ISSUE TITLE
undefined is not a function

### ISSUE THREAD

**Issue by JosephShering** [froala/angular-froala#2]
I'm getting this error when the program tries to run

`element.editable('setHTML', ngModel.$viewValue || '', false);`

I believe that it's refering to editable being undefined. I have jquery 2.1.1 script before angular and angular-froala but I still get this error. Do you have any idea what this might be?

**Comment by rickerd** [comment]
Hi, i'm also finding troubles with this thing.
I cannot get the editor to work since i switched to the new repository for the v2.* rc3

Here's my bower and grunt file.
"dependencies": {
    "angular": "angularjs#~1.4.7",
    "angular-bootstrap": "~0.13.0",
    "bootstrap": "~3.3.5",
    "grunt": "~0.4.5",
    "jquery": "~2.1.4",
    "font-awesome": "fontawesome#~4.4.0",
    "FroalaWysiwygEditor": "froala-wysiwyg-editor#v2.0.0-rc.3",
    "angular-froala": "~1.2.8",
    "install": "~1.0.4"
  }

[
                    'bower_components/jquery/dist/jquery.js',
                    'bower_components/angular/angular.js',
                    'bower_components/angular-froala/src/angular-froala.js',
                    'bower_components/angular-froala/src/froala-sanitize.js',
                    'bower_components/FroalaWysiwygEditor/js/froala_editor.min.js'
                ]

**Comment by cgallarno** [comment]
@rickerd It appears that you're not using the editorV.2 branch of angular-frola which is needed for froala 2.0.

Try changing value of `angular-froala` *from* "~1.2.8" *to* `https://github.com/froala/angular-froala#editorV.2` in your dependencies list.

**Comment by rickerd** [comment]
Got it working,
Sorry for the stupidity

---

Met vriendelijke groet,
Rick de Graaff

Verstuurd vanaf mijn iPhone 6

**Comment by cgallarno** [comment]
No Worries, if you feel the documentation could be more clear feel free to submit a pull request.
