### ISSUE TITLE
change the froalaOptions dynamically

### ISSUE THREAD

**Issue by TonyWoo** [froala/angular-froala#20]
For below example, when uploading a file I need to pass a orderid to the "upload_file" url, but the orderid may be changed by user dynamically. Will the directive monitor the $scope.froalaOptions changes? If not, how can I do this? Thanks in advance.

function myCtrl($scope){
    $scope.myHtml = "Hello World"
    $scope.froalaOptions = {
        fileUploadURL: '/upload_file?orderid=XXXXXXXX'
    }
}

**Comment by cgallarno** [comment]
Hello @TonyWoo,

The directive does have a `$scope.watch` on the options object passed to the directive and since the fileUploadURL is one of the options that be changed after initialization it should update, please reopen if this is not the case for you.
