### ISSUE TITLE
When can we expect 'froala events' to be completed?

### ISSUE THREAD

**Issue by salttechno** [froala/angular-froala#21]
Thanks for the great angular plugin. When can I use 'froala events' in angular plugin?

If you are not planning to release it soon, can you please guide me how can I use it?

**Comment by cgallarno** [comment]
Hey @salttechno, 

Events have been supported however I hadn't updated the readme to reflect that, the readme has been updated to include examples on how to use froala's events. Thank You!

**Comment by salttechno** [comment]
Thanks a lot for such a quick response! :+1:
