### ISSUE TITLE
Manual Initialization broken in V3 [BUG]

### ISSUE THREAD

**Issue by mikkoSarapelto** [froala/angular-froala#211]
##### Behavior:
Using initControls.initialize() doesn't succesfully init the editor. The toolbars are loaded correctly, but only [object HTMLDivElement] will be displayed where the editor window should be. Destroying the editor makes the toolbars disappear, but doesn't actually destroy the editor (initControls.getEditor() != null).

##### Steps to reproduce the problem:
It's broken in the demo too... Sample 3.

##### Editor version:
Angular Froala: V3.0
WYSIWYG: V3.0

##### Browser:
Chrome (75)

**Comment by navneetnagpal** [comment]
Fixed!
