### ISSUE TITLE
ReferenceError: FroalaEditor is not defined

### ISSUE THREAD

**Issue by Lelya** [froala/angular-froala#217]
Hello! Installed your bundle. But he not working. A copy of the repository from github.

**./node_modules/angular-froala**
```
 "name": "angular-froala",
  "version": "3.0.5",
```
**./node_modules/froala-editor**
```
  "name": "froala-editor",
  "version": "3.0.5",
```

```
errorCatcher.js:21 ReferenceError: FroalaEditor is not defined
    at Object.ctrl.createEditor (angular-froala.js:119)
    at Object.ctrl.init (angular-froala.js:60)
    at Object.link (angular-froala.js:222)
    at angular.js:1388
    at angular.js:11260
    at invokeLinkFn (angular.js:11266)
    at nodeLinkFn (angular.js:10585)
    at compositeLinkFn (angular.js:9832)
    at compositeLinkFn (angular.js:9835)
    at compositeLinkFn (angular.js:9835)
```

In app.js

```
import 'froala-editor/js/froala_editor.min';
import 'angular-froala/src/angular-froala';
```
In template.html
` <textarea froala class="form-control" id="description" ng-model="$ctrl.description"></textarea>`

What could be the problem?

**Comment by shanthan-arepuri** [comment]
I'm having the same problem.

**Comment by OBoiria** [comment]
Hello ! I am having the same problem with version 3.0.6. Did you fix this issue yet ?

**Comment by annabplr** [comment]
Hello, I have the same problem. :(

**Comment by OBoiria** [comment]
You can go through the error by adding the following line : `import FroalaEditor from 'froala-editor/js/froala_editor.min'` at the very beginning of the file `angular-froala.js` in your node modules. However, this is only a hotfix !

**Comment by Techbinator** [comment]
You can add in the entry file so that you do not need to apply a hotfix directly in the lib

```
import FroalaEditor from "froala-editor/js/froala_editor.min.js";
global.FroalaEditor = FroalaEditor;
```

**Comment by Lelya** [comment]
Thank you, Techbinator!

**Comment by bsodmike** [comment]
This saved many many hours of hunting for a solution, thanks!

**Comment by RafiTahmid** [comment]
@Techbinator What is the entry file you mentioned earlier?
