### ISSUE TITLE
Unable to write text in froala editor in Protractor tests

### ISSUE THREAD

**Issue by Pranab16** [froala/angular-froala#22]
In protractor tests, for normal textarea we can write text using sendKeys function. But for froala editor, it throws error: ``` unknown element: cannot focus element ```

**Comment by stefanneculai** [comment]
You should probably get the editable element and try on that one. `$(your_selector).data('fa.editable').$element`.

**Comment by Pranab16** [comment]
In protractor, jquery functions doesn't work. 
It throws error for the mentioned code ``` TypeError: Object [object Object] has no method 'data' ```

**Comment by cgallarno** [comment]
@Pranab16 froala doesn't use a textarea, it uses content editable so all you should need to do it target the content editable element and then you should be able to sendKeys to it. You should be able to select it by `#froala-0 .froala-element`. `froala-0` is an auto-generated id, you can set the id to whatever you want by putting the id on the element with the directive.

**Comment by stefanneculai** [comment]
The best way to get the editable element is:
- v1: `$(selector).data('fa.editable').$element`
- v2: `$(selector).data('froala.editor').$el`
