### ISSUE TITLE
Froala editor issue with Angular

### ISSUE THREAD

**Issue by manikmi** [froala/angular-froala#23]
Hi,

I am using the Froala Editor with Angular on my site. I am getting issue 

"Froala requires jQuery, are you loading it before Angular? <textarea id="txtPostEditor" froala="addPost.froalaOptions" ng-model="addPost.welcomeMessage" class="ng-pristine ng-untouched ng-valid ng-isolate-scope""

Did anybody faced this issue? Please help.

Regards,
Manik Mittal

**Comment by manikmi** [comment]
Even though, I have kept the js file reference in the order

jquery
Froala
Angular
Angular-Froala

**Comment by casche** [comment]
I also get this

**Comment by canvasmanager** [comment]
How did you do that? Can you share some sample code?

**Comment by manikmi** [comment]
How did you do that? Can you share some sample code?

**Comment by casche** [comment]
sorry @manikmi I tried that again and it didn't work. I'm doing some debugging and it looks like the problem is not only applicable to angular-froala but froala in general. At least when using in conjunction with angular. 

```
$('#edit').editable({});
```
When that line executes it doesn't seem like Froala is loaded as $('#edit') exists but $('#edit').editable is undefined. 

Still investigating...

**Comment by casche** [comment]
@manikmi Are you using mail chimp by any chance? I found my issue, see here http://stackoverflow.com/questions/24599084/mailchimps-mcj-jquery-noconflicttrue-causing-conflict

The line 

```
<script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
```

caused some nastiness.

**Comment by manikmi** [comment]
Hi Chris,

I got pass my issue. I was using a js from saavn.com, which I removed. It
worked for me.

Thanks a lot for helping,
Manik Mittal

On Fri, May 29, 2015 at 7:17 AM, Chris Asche <notifications@github.com>
wrote:

> @manikmi <https://github.com/manikmi> Are you using mail chimp by any
> chance? I found my issue, see here
> http://stackoverflow.com/questions/24599084/mailchimps-mcj-jquery-noconflicttrue-causing-conflict
>
> The line
>
> <script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
>
> caused some nastiness.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/froala/angular-froala/issues/23#issuecomment-106652649>
> .
>



-- 
Regards,
Manik Mittal
