### ISSUE TITLE
Regarding inline mode

### ISSUE THREAD

**Issue by harshalkumar** [froala/angular-froala#25]
Hi,

I am using froala with angularjs. Some of the fields on my page require the inline mode to be set as false which I am doing by following code. 
.value('froalaConfig', {
    inlineMode: false,
    placeholder: 'Enter Text Here'
  });
Apart from this, on the same page I do need inline mode to be set as true for other field. Can you please guide me how can I do that ?

**Comment by stefanneculai** [comment]
You are setting the defaults that way. Please read **From Controller** from https://github.com/froala/angular-froala#options for setting the options from controller.

**Comment by cgallarno** [comment]
@harshalkumar also note: that when you set options in the controller it will also inherit the options set during config, so all you need to so the set inline Mode to false for those editors and it will still use all the existing config options.
