### ISSUE TITLE
Angular 1.3

### ISSUE THREAD

**Issue by chriswong929** [froala/angular-froala#26]
I was just wondering if and when you plan to move to Angular ~1.3

Currently, angular-froala is using angular ~1.2.22 but from my experiences, all the features work fine on angular 1.3.

Thanks

**Comment by daslicht** [comment]
How about AngularJS 1.4.3 ?

**Comment by julian-iFactory** [comment]
How about Angular 1.4.4 ?

**Comment by daslicht** [comment]
Thats why I exactly don't like Angular or other technologies with hard dependencies .
Just use Summernote which is free compared to Froala ...

**Comment by cgallarno** [comment]
I've removed the hard requirement on angular and implemented @julian-iFactory's fix for sanitize in the `editorV.2` branch.

**Comment by momadthenomad** [comment]
Has this been fixed in the latest froala v2.7.6 release?

**Comment by momadthenomad** [comment]
@cgallarno we've also run into this issue and used @julian-iFactory's fix but we don't see the fix in the current release of froala v2.8.1. Am I missing something?
