### ISSUE TITLE
Is angular-froala not support event afterImageUpload?

### ISSUE THREAD

**Issue by aci227** [froala/angular-froala#29]
i am using qiniu as my images upload server,because it return image url param name is "key" and not "link",so  i must handle the upload response by myself,but it didn't trig after image upload event,can there anyone help me,please? thank u very much!

**Comment by cgallarno** [comment]
@aci227 All the FroalaWysiwygEditor events need to be added to angular-froala manually so that the directive will know to listen for them. This commt (caaefed941f748fdb3cb06031858ae162b417450) should resolve the issue for you.
