### ISSUE TITLE
getting element.editable is not a function

### ISSUE THREAD

**Issue by kadosh1000** [froala/angular-froala#30]
hi I am getting the error: "element.editable is not a function",
what may cause that? i do include the froala-editor js file

**Comment by cgallarno** [comment]
@kadosh1000 can you reproduce this in the demo file of the project? if so what steps did you take to get to this?

**Comment by RonnieSan** [comment]
I'm getting the same thing.  Followed the directions exactly and get an 'element.editable is not a function' error in my console.

**Comment by stefanneculai** [comment]
Thanks @RonnieSan for letting us know the solution that worked for you.

**Comment by sneakersgames** [comment]
It's really confusing! Please update the readme.
