### ISSUE TITLE
Can't seem to render video link.

### ISSUE THREAD

**Issue by zunairzubair** [froala/angular-froala#31]
Hi,
I am currently using froala in test application.
I render my html using ui-bootstrap popover. But it is not rendering the videos i am attaching using links. Pictures and other stuff works fine though.
Am I missing anything? Or is there any problem?
Thanks.

**Comment by zunairzubair** [comment]
Found the issue. The angular-sanitize.js and froala-sanitize.js blocks the <iframe> tag, You have to place this iframe tag in the list of unblocked items.

**Comment by noyg** [comment]
@zunairzubair how did you manage to add this? did you modify the code of froala-sanitize.js ?

**Comment by zunairzubair** [comment]
@noyg yes. Just modify the blockElements variable and add the html tag you want.
