### ISSUE TITLE
Get Scope Model from Froala Focus Callback

### ISSUE THREAD

**Issue by shebbys** [froala/angular-froala#34]
I have multiple Froala editors on the screen at once and am trying to control them independantly through their associated models.  Problem is that the focus callback and button callbacks pass (e,editor) which doesn't give me model information.. I tried to override the callback with something like this (I was desperate) 

div(ng-repeat="template in templates")
	textarea(id="editor_{{$index}}",froala="froalaOptions" ng-model="template.value",froala-event-focus="setFocusTemplate(template)")

but of course it didn't work.  I want to avoid going the dom element to scope route since thats a debug thing.

Any ideas on how to make this type of approach work?

**Comment by cgallarno** [comment]
I'm curious. With the editor object that is passed back through the focus and button callbacks, could you get the ID of the editor (which is being set at the index of the template in templates) therefore parse the index from the id and get "1" from `#editor_1`, then get your model as `templates[1].value`?

**Comment by shebbys** [comment]
@cgallarno Doh - Of course!!  That approach works perfectly!

var ide = $(e.target).attr('id').split("_")[1];
var focus_on = $scope.templates[ide];

Thanks :)
