### ISSUE TITLE
When initializing angular-froala with value associated to the model the undo button is active

### ISSUE THREAD

**Issue by hiperlouro** [froala/angular-froala#35]
I have the following code:

```javascript
app.controller('rteController', function ($scope) {

                $scope.rteModel = "Hello world from AngularJS text area!";
                
                $scope.froalaOptionsRTE = {
                    height: 300,
                    width: 650,
                    inlineEdit: false,
                
                };
});

```

```html
  <textarea id="area" froala="froalaOptionsRTE" ng-model="rteModel" ></textarea>
```

And when the page loads, the froala editor displays the undo button enabled.

If I press the undo button it clears the text.
Is it possible to change it to disable the undo button upon initialization? Or is this a bug?

Thanks.

**Comment by cgallarno** [comment]
@hiperlouro this is a side effect because of the way the html was set on initiation, this commit (fa0143fd0a1c3882fe45d897b5d14ce8ac80acf5) resolves this issue.

**Comment by hiperlouro** [comment]
Thanks for the quick fix! :+1:
