### ISSUE TITLE
Documentation - missing closing Tag in https://github.com/froala/angular-froala/blob/master/README.md

### ISSUE THREAD

**Issue by maximilianschmid** [froala/angular-froala#36]
https://github.com/froala/angular-froala/blob/master/README.md

<textarea froala ng-model="myHtml"><textarea>
should be 
<textarea froala ng-model="myHtml"></textarea>

The non closing textarea tag causes rendering issues with angularJS.

**Comment by cgallarno** [comment]
Thank you, I have updated the readme
