### ISSUE TITLE
Getting Unlicensed Froala Editor

### ISSUE THREAD

**Issue by andreyluiz** [froala/angular-froala#38]
Hi guys.

When I try to use the angular-froala, I get the following message in my textarea.

![](http://i.imgur.com/jIQ8e8b.png)

I got in touch with the Froala developers asking for a trial of the product. The answer was that it is just to download the editor from the site (there's a bower version, but I'm not sure if it is the same of the site) and use it. It is true because the examples in the zip package worked properly.

But when I try to use the angular-froala with the bower version of froala editor, this messagem appears. I tried to replace the files in the bower directory for the downloaded ones. But nothing happened.

Is this related to Froala itself, or it is a bug of angular-froala?

Thanks.

**Comment by stefanneculai** [comment]
There is no issue. When using the editor without a license you won't see the message on localhost or when you simply open the file.

**Comment by andreyluiz** [comment]
Ah, okay! I got it. Thank you.
