### ISSUE TITLE
ng-bind-html sanitizes formated text like font size, family and alignments

### ISSUE THREAD

**Issue by eddcvjm** [froala/angular-froala#40]
The following issue was found with the following versions:
 - SO: Windows 8.1
 - Browser: IE11 and also tested on Chrome
 - Froala: 1.2.8 and also tested on 2.x

We have the following text produced through the editor:

![image](https://cloud.githubusercontent.com/assets/13676411/9664690/6c9315f8-5263-11e5-87fa-9c53415b467d.png)

The resulting html is the following one:

![image](https://cloud.githubusercontent.com/assets/13676411/9664840/3aa858d6-5264-11e5-81d6-c156c4213d40.png)

But if we try to render the text using ng-bind-html, the result is:

![image](https://cloud.githubusercontent.com/assets/13676411/9664892/81beb198-5264-11e5-93cf-a85b9f0c686d.png)

If we use $sce.trustAsHtml to avoid sanitize, even using the froala-sanitize.js instead of the angular one, the text is rendered correctly, BUT if for some reason javascript like the following one is injected in the text

![image](https://cloud.githubusercontent.com/assets/13676411/9664970/08916d64-5265-11e5-9953-19043f53765c.png)

the alert popup gets fired.

There should be the possibility to render all kind of html generated by the froala editor, without having to disable sanitize.

Thanks

**Comment by cgallarno** [comment]
@eddcvjm Are you including angular-sanitize? angular-sanitize will remove the inline style tags and needs to be replaced by froala-sanitize which should maintain the styles.

**Comment by eddcvjm** [comment]
Hi,
I have the following code in my index.html and app.js
As you can see I have the code in my index.html

<script src="https://code.angularjs.org/1.2.5/angular.min.js"></script>

<script src="../src/froala-sanitize.js"></script>
<script src="../src/angular-froala.js"></script>

So, I'm assuming that I'm using the froala-sanitize.

But as you can see in my app.js, if I set $scope.myHtml without
$sce.trustAsHtml, the rendering looses all formatting.
If I set $scope.myHtml with $sce.trustAsHtml, the javascript is fired.


Thanks

2015-09-03 18:16 GMT+01:00 Cameron Gallarno <notifications@github.com>:

**Comment by j-hogue** [comment]
I am seeing the same issue, any progress?

**Comment by cgallarno** [comment]
@j-hogue can you submit a pull request?

**Comment by yanivlllev** [comment]
hi, did this issue solve? 
i'm experiencing the same thing.

**Comment by cgallarno** [comment]
I have added support for these attributes to froala-sanitize in this commit 1f8dfc10accde788eeec1736a1ed46f31763da77, we're working on a 'catch-all' solution to support all style attributes.
