### ISSUE TITLE
Angular Froala at runtime

### ISSUE THREAD

**Issue by manikmi** [froala/angular-froala#41]
Hi,

Is there a way to generate the Angular Froala Editor at runtime. I have a directive inside whichi want to generate the Froala Editor at the click of a button. I dont want to have the HTML in place before the button click. It is like clicking on the Edit button and the existing html converts to Froala Editor for editing.
Thanks in advance,
Manik Mittal

**Comment by cgallarno** [comment]
Hey @manikmi, 

Is there a reason for not wanting the editor html in place? I acheive a similar effect where I have a block of html that displays the content and another block of html that contains the editor, and I toggle the visibility of each block using ng-if.

**Comment by manikmi** [comment]
I require Editor as part of my directive, which is running inside a loop of many items loaded on the screen. If we have HTML in place in the directive, then for all the items, the html will be loaded and unnecessarily will load the page. what I want is to have a button in my directive, which when clicked for the specific item, the Froala Editor gets loaded up only for that item and on close, destroy it.

**Comment by cgallarno** [comment]
Have you tried froala's 'initOnClick' option? https://www.froala.com/wysiwyg-editor/docs/options#initOnClick

**Comment by manikmi** [comment]
Thank you Cameron for response,

I tried this option, but I got error for "editable function not found". May be some thing I am missing. Is it the scope that needs to corrected.

P.S. I am trying to initiate new Froala Editor inside of my directive at runtime.

Truly appreciate your help.

**Comment by manikmi** [comment]
I want to do something like https://www.froala.com/wysiwyg-editor/docs/examples/destroy-init
in my directive.

**Comment by manikmi** [comment]
Actually it worked for me now.Thanks a lot for help.
