### ISSUE TITLE
All http methods are not intercepted by interceptor

### ISSUE THREAD

**Issue by kotmatpockuh** [froala/angular-froala#43]
It's a really huge architecture bug. Angular lib (as you named it) is working not in angular way:

for example $http for image upload is not intercepted.

Thank you for your time.

**Comment by stefanneculai** [comment]
Same with #4 .

**Comment by kotmatpockuh** [comment]
NO @stefanneculai it's not the same!
#4 allow's to set custom header's, but it doesn't have anything with angular interceptor (which can caught 401 and make recall with refresh token to get new token, and repost this query)
your solution only set custom header, that what  #4  do.

**Comment by stefanneculai** [comment]
@cgallarno any thoughts about this one?

**Comment by cgallarno** [comment]
@kotmatpockuh Correct, angular can not intercept the http requests made from froala. 'anuglar-froala' is a simple directive wrapping the functionality of froala's WYSIWYG editor which is built in jQuery. If you need angular in control of the http requests, simply handle the upload with angular in the `beforeImageUpload` and return false out of that function so that froala won't attempt an upload.

**Comment by kotmatpockuh** [comment]
@cgallarno yes...
i can return false... but maybe you have ideas, how to (for example) set waiter for example for 3sec (until new token received) and then only run froala upload?

**Comment by kotmatpockuh** [comment]
if i will return false, then only upload modal is hidden

**Comment by cgallarno** [comment]
@kotmatpockuh So when you return false, froala still uploads the image? @stefanneculai is there a way that you can cancel the http request, then run an asynchronous function to determine if the image is allowed to be uploaded (in angular) and if so, manually re-trigger/resume the upload?

**Comment by kotmatpockuh** [comment]
@cgallarno no - it didn't, but it close the upload popup - and user didn't know, what happens even (nothing)

**Comment by kotmatpockuh** [comment]
all i need - only method-callback-event for uploading, like beforeImageUpload - there i will check: my token is valid, then run upload - no, than no

**Comment by cgallarno** [comment]
In my implementation we handle the image upload ourselves, here is the gist of our code in `beforeImageUpload`

```javascript
editor.saveSelection();
//hides the "drag image here" box
editor.$popup_editor.find("div[id^='f-image-list-']").hide();

//Shows image popup
editor.$popup_editor.find('.froala-image-popup').show();
var progressBar = editor.$progress_bar.find('span');
//Show the progress bar
editor.$progress_bar.show();

//Handle image upload
     //On success
        editor.restoreSelection();
	editor.writeImage(imageUrl);

    //On Notify
	if (evt.lengthComputable) {
		var complete = (evt.loaded / evt.total * 100 | 0);
                //update progress bar
		progressBar.width(complete + '%');
         
		if(complete == 100){
                        // Our server has some post upload processing
                        // So continue to show the progress bar with context until call is completed
			progressBar.text("Preparing");
		}else{
			$log.log("Progress: " + complete);
		}
	}


return false;
```

**Comment by stefanneculai** [comment]
The method used by @cgallarno is the way to go.

**Comment by kotmatpockuh** [comment]
@cgallarno it's strange... but with your gist loader popup is not displayed, only if i set debugger breakpoint it appear O_o

**Comment by cgallarno** [comment]
try wrapping it in an empty setTimeout, like so:

```javascript
setTimeout(function(){
    editor.$popup_editor.find('.froala-image-popup').show();
});
```

Also to note, I'm using this with V1 of the editor.

**Comment by kotmatpockuh** [comment]
yes, i unterstand (about v1)
unfortunatelly timeout didn't solve it...
but thank you)
maybe you have some ideas, how to use loader with $http?
like get percentage:
```

   $http.post(settings.apiBaseUri + '/files', fd, {
              withCredentials: true,
              headers: {
                'Content-Type': undefined
              },
              transformRequest: angular.identity
            })
            .success(function(response) {
              editor.restoreSelection();
              editor.writeImage(response.link);
            })
            .error(function(err, status) {
            });

```

**Comment by kotmatpockuh** [comment]
@cgallarno 
i understood: '.froala-image-popup' is hidding all time when i click somewhere else, while image is loading (when using default code, loading popup isn't hiding never, while image is uploading)

trying to figure out, what is "wrong"

**Comment by cgallarno** [comment]
For me, while an image is uploading when I click outside the popup does disappear but so does the progress bar, when I click on the image icons the pop up appears with the current progress of the upload. I see no problem here. It that's what's happening for you?

**Comment by kotmatpockuh** [comment]
@cgallarno yes, i see the same behavior
but as for me, it's unclear, when progress bar popup is closed, while loading image...

**Comment by cgallarno** [comment]
Do you desire to keep the image popup visible while the image is still uploading, so that clicking outside of it will *not* hide it? @stefanneculai Do you know how to achieve this?

**Comment by kotmatpockuh** [comment]
@cgallarno yep... i mean directly that...

btw, seems that i solved it in simple way:
```
...
imageError: function(e, editor, error) {
  if (error.code !== 3){
    /**/
  }
  else{
    uploaderService.addImage($scope.fileToUpl).then(function(url) {
      editor.writeImage(url.link);
    });
  }
},
beforeImageUpload: function(evt, editor, images) {
  $scope.fileToUpl = images[0];
},
...
```

**Comment by kotmatpockuh** [comment]
btw, @stefanneculai in v2.* there is a method in image, called 'hideProgressBar'. When i call it - it hide not only popup, but image as well.
Strange behavior...

**Comment by stefanneculai** [comment]
On hiding the image progress bar, if there is an image which wasn't uploaded successfully, then it is being removed as well. That is the correct behaviour.
