### ISSUE TITLE
Object doesn't support property or method 'editable'

### ISSUE THREAD

**Issue by DeanWilliamMills** [froala/angular-froala#47]
Hi.

I get the following error:

Object doesn't support property or method 'editable'
at link (../angular-froala.js:82:5)

it is this line "var froala = element.editable(options).data('fa.editable');"

I appreciate your help. Thank you

**Comment by cgallarno** [comment]
I think you are trying to use version two of the editor with version one of the angular adapter. If you are using 2.0 of the wysiwyg editor be sure to use the editorV.2 branch on this project.

**Comment by cgallarno** [comment]
@DeanWilliamMills Did you get your problem solved or is this still open?
