### ISSUE TITLE
my click not working

### ISSUE THREAD

**Issue by longxianlin** [froala/angular-froala#48]
add textarea by click. not working

```javascript
$scope.addTextArea = function(){
    console.log("添加文本");
    var contentWrap = $('#contentWrap');
    console.log(contentWrap);
    contentWrap.append("<textarea froala='froalaOptions' ng-model='myHtml'></textarea>");
  };

  $scope.froalaOptions = {
        buttons : ["bold", "italic", "underline", "sep", "align", "insertOrderedList", "insertUnorderedList"]
    };

```

**Comment by cgallarno** [comment]
@longxianlin That is because you're using jQuery to add the html and angular is 'unaware' of the changes to the dom. You will need to add the new html with angular's $compileProvider so that it is interpreted with AngularJS. https://docs.angularjs.org/api/ng/service/$compile
