### ISSUE TITLE
Froala sanitizer is wiping out the float property

### ISSUE THREAD

**Issue by harshalkumar** [froala/angular-froala#49]
I am trying to upload the image with image title. But sometimes froala is wiping out the image title and float property of the image while normalization or sanitization process. This is happening very frequently. Any help will be really appreciated.

**Comment by cgallarno** [comment]
@harshalkumar The float property shouldn't be removed, but the title attribute isn't whitelisted by froala-sanitize. I don't see a way to add a title to an image with the editor. How is the title getting added? Is there a way you can reproduce this ?

**Comment by cgallarno** [comment]
Fixed by this commit: https://github.com/froala/angular-froala/commit/895b45a93bf5f0f26ca945b8645e5645f838c7dc
