### ISSUE TITLE
use strict in global scope may break when concatenated

### ISSUE THREAD

**Issue by warpdesign** [froala/angular-froala#50]
It seems that the main file angular-froala.js has a use strict defined at the begining of the file:

    use strict;
    // code starts here

So if this file is concatenated with other files, it may break since it will apply use strict; to everything that is concatenated.

I would suggest wrapping code inside a closure (that's what mostly every projects do):

    (function() {
       use strict;
       // code starts here
    )}():

This way use strict; is restricted to froala's code and won't impact any other code.

**Comment by cgallarno** [comment]
@warpdesign Where are you seeing this? "use strict"; is inside the angular-froala directive

**Comment by warpdesign** [comment]
@cgallarno The tagged release 1.2.8 (https://github.com/froala/angular-froala/archive/1.2.8.zip) which is the version that gets installed through bower contains a version of the directive with the "use strict" outside of the directive.

Current Git version doesn't have the version indeed.

**Comment by warpdesign** [comment]
The bug seems to have been fixed in 2.0rc: a possible workaround is to force the "v2.0.0-rc.3" version in bower.json when adding angular-froala as a dependency.

**Comment by stefanneculai** [comment]
@warpdesign it's updated to V2.0.1 now.

**Comment by warpdesign** [comment]
@stefanneculai ok, thanks!
