### ISSUE TITLE
image upload with Authorization header

### ISSUE THREAD

**Issue by felixroos** [froala/angular-froala#51]
Hello!
First of all: Thank you for this grandiose WYSIWYG editor! I am currently evaluating it and consider using it for our new product. Everything is perfect for now except one thing: image upload.
My goal is to upload images from froala to our server. 
At first, I followed the [image upload concept](https://www.froala.com/wysiwyg-editor/docs/concepts/image-upload) but it lacks a possiblity to set the HTTP Authorization header, which is a requirement of our API to specify an accessToken (more info [here](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html)).
Second, I tried to take the internal froala upload out of the equation by using the beforeImageUpload event:
```javascript
$scope.froalaOptions = {
  buttons: ["bold", "italic", "underline", "sep", "fontFamily", "fontSize", "color", "sep", "align", "emoticons",
            "insertOrderedList", "formatOL", "insertUnorderedList", "sep", "insertLink", "insertTable", "insertImage",
            "insertVideo", "paragraphFormat", "paragraphStyle", "quote", "html", "sep", "fullscreen"],
  events:  {
    beforeImageUpload: function(e, editor, images) {
      $scope.uploadFirstImage(images).then(function(url) {
        console.log(url);
        $scope.froalaOptions.froala("insertImage", url);
      });
      return false;
    },
    imageError:        function(e, editor, error) {
      console.log(error);
    }
  }
};
```
The uploadFirstImage function sends the first of images to our server and resolves the url (works). But the [insertImage](https://www.froala.com/wysiwyg-editor/docs/methods#image.insert) Method of froala does not insert the image by URL. I then tested calling the insertImage method from the outside (on a button click) and realized it just opens the insertImage overlay, the given URL is ignored. Either a method to insert an Image by URL directly is required here, or (even better) a possibility to pass an authorization header. Would you agree with that feature request? If yes I could also offer to dig myself into the code and send a pull request.
Keep up the very good work!
Greetings from Germany,
Felix

**Comment by stefanneculai** [comment]
Would it be possible to make a JS fiddle for it?

**Comment by felixroos** [comment]
[http://jsfiddle.net/8g6aq30x/6/](This fiddle) shows the insertImage function. As I understand it, the method should insert the image with the specified URL into the editor, but what happens is that the overlay opens, the URL is ignored.

**Comment by stefanneculai** [comment]
It looks you're using the older version V1.2. The method is called writeImage: http://jsfiddle.net/0k8bx312/.

For V2 please see: https://github.com/froala/angular-froala/tree/editorV.2.

**Comment by felixroos** [comment]
Ahh okay I did not know of the writeImage method (already got the new version). It is still missing on the [Methods Page](https://www.froala.com/wysiwyg-editor/docs/methods) (where I got my info). Thank you for the hyper fast feedback!! Now my workaround is working around :)
