### ISSUE TITLE
Multi-lang support

### ISSUE THREAD

**Issue by mehowp** [froala/angular-froala#52]
This module does not allow to implement different language while using RequireJS.

**Comment by mehowp** [comment]
Here's another problem with fraola plugins:
http://stackoverflow.com/questions/33919735/uncaught-referenceerror-module-is-not-defined-requirejs/33920006?noredirect=1#comment55603059_33920006

**Comment by mehowp** [comment]
Your "bower install angular-froala" installs also "froala-wysiwyg-editor" bad have bad source of plugins code, please replace them with [correct one](https://github.com/froala/wysiwyg-editor) .

**Comment by stefanneculai** [comment]
@mehowp that will be done on release of v2.0.2.

**Comment by EvilJohnny** [comment]
I would also like to see the mutilanguage support!

I thought it would be just adding the ```language``` option in the options passed.. but just tested and it doesn't work :sweat_smile: 

Any estimated time for the 2.0.2 release, @stefanneculai ? :smiley:

**Comment by stefanneculai** [comment]
@EvilJohnny we don't have an ETA yet.

**Comment by stefanneculai** [comment]
Updated to v2.0.2.

**Comment by EvilJohnny** [comment]
Weeee! Thanks!

(I just realized that @mehowp said "using Require JS"... I am not using it, so maybe this was already working before for me and I had some coding error :sweat_smile: )
