### ISSUE TITLE
In code view, ngModel is not updated

### ISSUE THREAD

**Issue by ericleethrinacia** [froala/angular-froala#56]
I tried saving the data that the <textarea froala ng-model="data"> is bound to via ng-model but data is not updated when switched to code view. Triggering contentUpdated event doesn't seem to work as I notice in text view, the editor generates the HTML in a <div> but in code view it's they are texts in a textarea. 
Would that be why?
Is there anyway around this besides switching back to text view whenever I want to save the "data"?

**Comment by stefanneculai** [comment]
With the latest master of the editor the contentChanged event should be triggered before form submit and the editor shouldn't toggle back to the text view. Could you please try it and let me know if it fixes the problem?

**Comment by ericleethrinacia** [comment]
Oh but I am just simply retrieving the "data" that is bound to the froala editor via ng-model by $scope.data
Is there a way just for this to update ngModel? Or what's triggering the contentChanged event in code view so I can make little adjustment

**Comment by stefanneculai** [comment]
https://github.com/froala/angular-froala/blob/master/src/angular-froala.js#L57 should do that.

**Comment by ericleethrinacia** [comment]
It does in text view but not in code view when I have a button that has ngClick to run a function that saves the content in the editor along with other stuffs
Right now I'm calling 
$rootScope.froalaOptions.froalaEditor("codeView.toggle");
twice so it updates and and stay in same view. But in some cases the second call doesn't toggle and undo button stays lit up

**Comment by stefanneculai** [comment]
With the [latest master version](https://github.com/froala/wysiwyg-editor) that is no longer necessary.

**Comment by ericleethrinacia** [comment]
Can you please go to origin.thrinacia.com and navigate to admin/pages/edit blog posts
Edit in code view and refresh to see if it actually saves please

**Comment by stefanneculai** [comment]
When using the code view, the contentChanged event is triggered only in 2 cases: switch to text view or submit the form.

**Comment by ericleethrinacia** [comment]
Thank you
I made it work by manually calling the form.submit event
