### ISSUE TITLE
editInPopup and Placeholder

### ISSUE THREAD

**Issue by yanivlllev** [froala/angular-froala#58]
Does the editInPopup has a placeholder option?
right now i have several Froalas, all are fine with placeholders, but when i config one of them to be type "editInPopup", it doesn't have a placeholder anymore, and if i delete the text, i can't re-edit it, it's like it disappeared even that the element is still in the DOM.

any ideas why?

**Comment by cgallarno** [comment]
@yanivlllev I think that the element is still there, but there is no text in it so it may have 0 width or height if it's an inline element. As for the placeholder, @stefanneculai Does the `editInPopup` option support the `placeholderText` option? here's a possible workaround to have a default value if your model is empty.

```javascript
$scope.$watch('myModel', function(nv, ov){
     if (nv == undefined || nv.length == 0){
          $scope.myModel = 'Edit Me';
     }
});
```

**Comment by stefanneculai** [comment]
With the last commit, when there is no text entered, the `placeholderText` option will be used.
