### ISSUE TITLE
Froala validate required field

### ISSUE THREAD

**Issue by naneri** [froala/angular-froala#60]
When I am setting "required" attribute on Froala textarea - it still  allows me to pass blank spaces as an input (which is for example not allowed in TEXT inputs). How can I prevent this and achieve the same behavior as with casual TEXT inputs?

**Comment by cgallarno** [comment]
@naneri the `required` attributed is now acknowledged with this commit https://github.com/froala/angular-froala/commit/4f0822d313adc9e6a5a53644ead7899734b64b99

**Comment by naneri** [comment]
@cgallarno thanks for the update. When will that update get to bower?

**Comment by cgallarno** [comment]
@naneri angular-froala's tags sync up with froala's tagged updates. @stefanneculai are there any tagged updated planned in the near term?

**Comment by naneri** [comment]
@cgallarno ok, thanks for the info. I will be waiting for the update.
