### ISSUE TITLE
froala editor resets model

### ISSUE THREAD

**Issue by samvloeberghs** [froala/angular-froala#65]
When using the  froala editor my model gets reset.
When typing into the editor, the model doesn't get updated. But when you do a selection and make bold for example, it does update the model.

So for example:
So I have a controller: "Controller" and this is coupled to a view with an input and a textarea.
The textarea has the froala directive on it.

Controller:

```
this.model = {
    'title': 'title',
    'answer': 'answer'
}
```

and answer is bound to the editor.

If you output it in the view,  using

```
<pre>
{{
 Controller.model | json
}}
</pre>
```

it prints:

```
{
  'title': 'title'
}
```

When typing in editor there is no modification, so the view stays as above. 
But after selecting and making the contents of the editor bold, the view updates the update for the model as:

```
{
  'title': 'title',
  'answer': '<p><strong>answer</strong></p>
}
```

~~It only seems to be the problem when the initial value is no HTML!~~
Edit: It is also the case when the model has HTML, but the model is still reset, and only get's filled in after doing an action in the toolbar!

Grtz

**Comment by samvloeberghs** [comment]
It' also only working on setting bold. When I click underline or italic, it doesn't do anything..
This has some really weird behaviour :) For 100$ I expect more

**Comment by samvloeberghs** [comment]
After further investigation it seems that editor doesn't like child properties of an object on the scope.
If the value in the ng-model is a direct value on the scope it seems to work. Please fix this?

**Comment by cgallarno** [comment]
@samvloeberghs Hmm, that's strange as my model is a property on an object thats on scope and it works fine. I'll look into this.
