### ISSUE TITLE
Character Count not showing on initialized content

### ISSUE THREAD

**Issue by jester12345** [froala/angular-froala#68]
If I load the character count plug-in, it successfully loads and shows 0/1500 or whatever. However, I'm preloading content and that is not being considered in the count. As soon as I type a character, the character count updates correctly. It's just not initializing correctly when the model has content already.

Should I be doing something to trigger the character count to initialize on the "froalaEditor.initialized" event?

Thanks for your help!

**Comment by stefanneculai** [comment]
Calling [events.trigger('charCounter.update')](https://www.froala.com/wysiwyg-editor/docs/methods#events.trigger) method should update the charCounter.

**Comment by jester12345** [comment]
It worked! Thanks for your help.

**Comment by ravindueranga** [comment]
I have it like this,
```
            evdc.editorOptions = {
		events : {
			'froalaEditor.initialized' : function() {
			
			}
		},			
		charCounterMax : 200
             };
```

How can I `add events.trigger('charCounter.update')` in here?

**Comment by jester12345** [comment]
I actually ended up calling it this way:
`$(this).froalaEditor('events.trigger', 'charCounter.update');`
But it looks to me like they way you are doing it should should work. As long as you are giving it content prior to initialization. If it's after Froala has initialized, then you might want:

```
events : {
  'froalaEditor.html.set': function (e, editor) {
    editor.events.trigger('charCounter.update');
  }
}
```

**Comment by ravindueranga** [comment]
Hey @jester12345 actually your code worked. Thanks

**Comment by heshanrandika** [comment]
below code is not working anymore.

events : {
  'froalaEditor.html.set': function (e, editor) {
    editor.events.trigger('charCounter.update');
  }
}

**Comment by heshanrandika** [comment]
Hey @jester12345 your below code is not working anymore.

` events : {
   'froalaEditor.html.set': function (e, editor) {
     editor.events.trigger('charCounter.update');
   }
} `

**Comment by yogeshsingh0574** [comment]
hey @jester12345 thanks it worked.
