### ISSUE TITLE
Error using Froala Editor in Ionic hybrid app.

### ISSUE THREAD

**Issue by pine0510** [froala/angular-froala#69]
I am developing a forum app using Ionic framework.
And using froala editor.
I followed this tutorial https://github.com/froala/angular-froala
But if I add &lt;textarea froala="froalaOptions" ng-model="myHtml"&gt;&lt;/textarea&gt;  in my html file, only textarea is displayed and i can see error on console

Error: element.froalaEditor is not a function. (In 'element.froalaEditor(ctrl.options)', 'element.froalaEditor' is undefined) init@http://localhost:8100/lib/angular-froala.js:36:50 link@http://localhost:8100/lib/angular-froala.js:86:14 http://localhost:8100/lib/ionic/js/ionic.bundle.js:21956:49 invokeLinkFn@http://localhost:8100/lib/ionic/js/ionic.bundle.js:21962:15 nodeLinkFn@http://localhost:8100/lib/ionic/js/ionic.bundle.js:21462:23 compositeLinkFn@http://localhost:8100/lib/ionic/js/ionic.bundle.js:20853:23 compositeLinkFn@http://localhost:8100/lib/ionic/js/ionic.bundle.js:20857:24 nodeLinkFn@http://localhost:8100/lib/ionic/js/ionic.bundle.js:21457:35 compositeLinkFn@http://localhost:8100/lib/ionic/js/ionic.bundle.js:20853:23 nodeLinkFn@http://localhost:8100/lib/ionic/js/ionic.bundle.js:21457:35 compositeLinkFn@http://localhost:8100/lib/ionic/js/ionic.bundle.js:20853:23 publicLinkFn@http://localhost:8100/lib/ionic/js/ionic.bundle.js:20728:45 appendViewElement@http://localhost:8100/lib/ionic/js/ionic.bundle.js:56890:11 render@http://localhost:8100/lib/ionic/js/ionic.bundle.js:54995:58 init@http://localhost:8100/lib/ionic/js/ionic.bundle.js:54915:26 render@http://localhost:8100/lib/ionic/js/ionic.bundle.js:56743:18 register@http://localhost:8100/lib/ionic/js/ionic.bundle.js:56701:16 updateView@http://localhost:8100/lib/ionic/js/ionic.bundle.js:62357:31 http://localhost:8100/lib/ionic/js/ionic.bundle.js:62334:21 $broadcast@http://localhost:8100/lib/ionic/js/ionic.bundle.js:29477:33 http://localhost:8100/lib/ionic/js/ionic.bundle.js:49321:32 processQueue@http://localhost:8100/lib/ionic/js/ionic.bundle.js:27879:30 http://localhost:8100/lib/ionic/js/ionic.bundle.js:27895:39 $eval@http://localhost:8100/lib/ionic/js/ionic.bundle.js:29158:28 $digest@http://localhost:8100/lib/ionic/js/ionic.bundle.js:28969:36 $apply@http://localhost:8100/lib/ionic/js/ionic.bundle.js:29263:31 done@http://localhost:8100/lib/ionic/js/ionic.bundle.js:23676:53 completeRequest@http://localhost:8100/lib/ionic/js/ionic.bundle.js:23848:15 requestLoaded@http://localhost:8100/lib/ionic/js/ionic.bundle.js:23789:24

**Comment by cgallarno** [comment]
@pine0510 are you including the `froala_editor.js` file in your project?

**Comment by OACDesigns** [comment]
I've just run into a similar issue (using gulp to concat and minify all js files into a single file)
You need to make sure `jquery.js` is added *before* the main `angular.js` file, otherwise angular will use it's own `jqLite` which doesn't have the required functions for froala to work.
