### ISSUE TITLE
Adding event to options not working

### ISSUE THREAD

**Issue by Nudelsieb** [froala/angular-froala#70]
The provided Events example does not work:
```javascript
$scope.froalaOptions = {
    placeholder: "Edit Me",
    events : {
        'froalaEditor.focus' : function(e, editor) {/* ... */}
    }
```

Sublime Text highlights wrong syntax, because it is an unnamed function. 

In my case, if I do
```javascript
events: {
      'froalaEditor.image.beforeUpload' : function(e, editor, images) {
        console.log("Ready to upload images: " + images);
      }
```
the controller breaks. How do I add events to the options object correctly?

**Comment by cgallarno** [comment]
@Nudelsieb Here's a snippet with option with and events that works fine for me.

```javascript
$scope.titleOptions = {
	placeholderText : 'Add a Title',
	events : {
		'froalaEditor.blur': function () {
			alert("Editor Blurred");
		}
	}
};
```

**Comment by Nudelsieb** [comment]
Oh that works fine, there must have been some other bug, thanks.

**Comment by cgallarno** [comment]
No Worries, if you feel the readme can be more clear feel free to submit a pull request.
