### ISSUE TITLE
some styles aren't saved - can't figure whats wrong

### ISSUE THREAD

**Issue by yanivlllev** [froala/angular-froala#72]
hey, i'm trying to figure out why some of the styles aren't applied to the view.

i wrote new custom dropdown for 'text direction' with 'rtl' and 'ltr' - i can see that it changes in the froala edit mode, but in view nothing happens.
also, i noticed that the default "font-size" and "font family" in the toolbar aren't applied.
any ideas for what's wrong?

this is the my custom dropdown configuration:

    function addDropdown() {
            $.FroalaEditor.DefineIcon("textDirection", {
                NAME: "cog"
            });
            $.FroalaEditor.RegisterCommand("textDirection", {
                title: "Text Direction",
                type: "dropdown",
                focus: true,
                undo: true,
                refreshAfterCallback: true,
                options: {
                    "ltr": "Left-To-Right",
                    "rtl": "Right-To-Left"
                },
                callback: function(cmd, val) {
                    if(val=='ltr') {
                        var dir = 'ltr',
                            align = 'left';
                    } else {
                        var dir = 'rtl',
                            align = 'right';
                    }
                    var changeDirection = function (dir, align) {
                        this.selection.save();
                        var elements = this.selection.blocks();
                        for (var i = 0; i < elements.length; i++) {
                            var element = elements[i];
                            if (element != this.$el.get(0)) {
                                $(element)
                                    .css('direction', dir)
                                    .css('text-align', align);
                            }
                        }

                        this.selection.restore();
                    }
                    changeDirection.apply(this, [dir, align]);

                },
                // Callback on refresh.
                refresh: function($btn) {
                },
                // Callback on dropdown show.
                refreshOnShow: function($btn, $dropdown) {
                }
            });
        }
        addDropdown();

this is the custom froala i use:

    $scope.froalaTopToolbar = {
            initOnClick: true,
            toolbarInline: false,
            toolbarSticky: true,
            toolbarStickyOffset: 128,
            toolbarButtons: ['textDirection','fullscreen', 'bold', 'italic', 'underline', 'strikeThrough', 'subscript', 'superscript', 'fontFamily',
                'fontSize', '|', 'color', 'emoticons', 'inlineStyle', 'paragraphStyle', '|', 'paragraphFormat', 'align', 'formatOL',
                'formatUL', 'outdent', 'indent', 'quote', 'insertHR', '|', 'insertLink', 'insertImage', 'insertVideo', 'insertFile',
                'insertTable', 'undo', 'redo', 'clearFormatting', 'selectAll', 'html'],
            events : {
                'froalaEditor.focus' : function(e, editor) {
                    editor.toolbar.show()
                },
                'froalaEditor.blur' : function(e, editor) {
                    editor.toolbar.hide()
                }
            }
        };

here's a screen shot:
![img](https://cloud.githubusercontent.com/assets/12447235/12713359/c2721520-c8d6-11e5-8360-597646001a16.jpg)

when i try to color the text, or do lists, or paragraph heading it works, but "font-size" and "font-family" and "direction" css aren't applied to the view.

edit mode html is:

    <div froala="froalaTopToolbar" ng-model="element.data.content"></div>

view is:

    <div class="fr-view" ng-bind-html="element.data.content"></div>

this is what's included in the app.js aggregation by the way:

        Theme.aggregateAsset('css', '../lib/froala-wysiwyg-editor/css/froala_editor.min.css');
    Theme.aggregateAsset('css', '../lib/froala-wysiwyg-editor/css/plugins/table.min.css');
    Theme.aggregateAsset('css', '../lib/froala-wysiwyg-editor/css/plugins/colors.min.css');

    Theme.aggregateAsset('js', '../lib/froala-wysiwyg-editor/js/froala_editor.min.js',  {weight: 1, global: true});
    Theme.aggregateAsset('js', '../lib/froala-wysiwyg-editor/js/plugins/align.min.js',  {weight: 2,global: true});
    Theme.aggregateAsset('js', '../lib/froala-wysiwyg-editor/js/plugins/url.min.js',  {weight: 2,global: true});
    Theme.aggregateAsset('js', '../lib/froala-wysiwyg-editor/js/plugins/table.min.js',  {weight: 2,global: true});
    Theme.aggregateAsset('js', '../lib/froala-wysiwyg-editor/js/plugins/link.min.js',  {weight: 2,global: true});
    Theme.aggregateAsset('js', '../lib/froala-wysiwyg-editor/js/plugins/lists.min.js',  {weight: 2,global: true});
    Theme.aggregateAsset('js', '../lib/froala-wysiwyg-editor/js/plugins/font_size.min.js',  {weight: 2,global: true});
    Theme.aggregateAsset('js', '../lib/froala-wysiwyg-editor/js/plugins/font_family.min.js',  {weight: 2,global: true});
    Theme.aggregateAsset('js', '../lib/froala-wysiwyg-editor/js/plugins/colors.min.js',  {weight: 2,global: true});
    Theme.aggregateAsset('js', '../lib/froala-wysiwyg-editor/js/plugins/paragraph_style.min.js',  {weight: 2,global: true});
    Theme.aggregateAsset('js', '../lib/froala-wysiwyg-editor/js/plugins/paragraph_format.min.js',  {weight: 2,global: true});
    Theme.aggregateAsset('js', '../lib/froala-wysiwyg-editor/js/plugins/inline_style.min.js',  {weight: 2,global: true});
    Theme.aggregateAsset('js', '../lib/angular-froala/src/angular-froala.js');
    Theme.aggregateAsset('js', '../lib/angular-froala/src/froala-sanitize.js');

**Comment by yanivlllev** [comment]
by the way, when added the following to the 'validStyles(styleAttr)' function in 'froala-sanitize.js' file - the direction css was saved and applied.
           
    ||
         key === 'direction' && (
                     value === 'ltr'
                     || value === 'rtl'
                )


but i still don't know how to solve it globally and what's wrong with the other styles like font-size and font-family.

**Comment by cgallarno** [comment]
@yanivlllev This commit should fix it e295480d3ba49d307ff015c5ef0c205d28821fcb, Thanks!
