### ISSUE TITLE
Embedded Videos Problems

### ISSUE THREAD

**Issue by mkteagle** [froala/angular-froala#74]
Embedded videos are not showing up in the ng-bind-html attributed element. I am using ngSanitize and I have included the froala santitize script.

Thanks,
Mike

**Comment by cgallarno** [comment]
@mkteagle We're still working on supporting all the tags that the froala editor enables users to use, while still keeping angular's security in mind.

For now, you can edit `froala-sanitize.js` and add `iframe` to the `blockElements` and the sanitizer shouldn't remove it when rendered.

**Comment by mkteagle** [comment]
Thank you!

**Comment by AElouai** [comment]
if any case changing the sanitize file doesn't resolve your problem you can  bind it  directly lile so 

```
<div class="fr-view" >
      <div ng-bind-html="article.content | to_trusted"></div>
</div>

```

```
.filter('to_trusted', ['$sce', function($sce){
    return function(text) {
        return $sce.trustAsHtml(text);
    };
}]);
```

**Comment by AElouai** [comment]
if any case changing the sanitize file doesn't resolve your problem you can bind it directly like so

```
<div class="fr-view" >
      <div ng-bind-html="article.content | trustedBind"></div>
</div>
```
```
.filter('trustedBind', ['$sce', function($sce){
    return function(text) {
        return $sce.trustAsHtml(text);
    };
}]);
```
