### ISSUE TITLE
froalaEditor never gets set as a property of froalaOptions

### ISSUE THREAD

**Issue by babilog** [froala/angular-froala#75]
Following the documentation provided on the ReadMe, I am not able to access the froalaEditor using  the followin:  $scope.froalaOptions.froalaEditor("selection.get");

I receive the following error: Object doesn't support property or method 'froalaEditor'

**Comment by cgallarno** [comment]
@babilog can you provide a code snippet? the froalaEditor object wont be immediately available, it's only after the editor has initialized that property is assigned.

**Comment by ment0sman** [comment]
I am having a similar issue, snippet below:

`        //froala-options
        $scope.froalaOptions = {
            toolbarButtons: ['fullscreen', 'bold', 'italic', 'underline', 'strikeThrough', 'subscript', 'superscript', 'fontFamily', 'fontSize', '|', 'color', 'inlineStyle', 'paragraphStyle', '|', 'paragraphFormat', 'align', 'formatOL', 'formatUL', 'outdent', 'indent', 'quote', '|', 'insertHR', '-', 'insertLink', 'insertImage', 'insertVideo', 'insertFile', 'insertTable', '|', 'undo', 'redo', 'clearFormatting', 'selectAll', 'html'],
            heightMin: 400,
            imageUploadURL: '/api/commshub/addimage'

        }

        $timeout(function () {
            $scope.froalaOptions.froalaEditor("events.focus");
        });`

**Comment by babilog** [comment]
@cgallarno Even when the editor comes into focus, the froalaEditor property is still undefined. Here's another snipped apart from the one @ment0sman .

`            $scope.froalaOptions = {
                toolbarButtons: ['fullscreen', 'bold', 'italic', 'underline', 'strikeThrough', 'subscript', 'superscript', 'fontFamily', 'fontSize', '|', 'color', 'inlineStyle', 'paragraphStyle', '|', 'paragraphFormat', 'align', 'formatOL', 'formatUL', 'outdent', 'indent', 'quote', '|', 'insertHR', '-', 'insertLink', 'insertImage', 'insertVideo', 'insertFile', 'insertTable', '|', 'undo', 'redo', 'clearFormatting', 'selectAll', 'html'],
                heightMin: 400

            }
            $scope.froalaOptions.froalaEditor({
                imageAllowedTypes: ['png']
            } );`

**Comment by cgallarno** [comment]
@babilog the froalaEditor can only take methods from https://www.froala.com/wysiwyg-editor/docs/methods, you cannot set or change options after the edit has been initialized.

**Comment by babilog** [comment]
@cgallarno Our main goal is to define an imageUploadURL on the event that an image is uploaded. How could we define that property? 

Even when I use the   $scope.froalaOptions.froalaEditor("selection.get"); after defining my options, I still receive the error. 

Thank you in advance.

**Comment by cgallarno** [comment]
I believe this is the same issue as https://github.com/froala/angular-froala/issues/64. @babilog can you try out those suggestions and see if any of them work?

**Comment by babilog** [comment]
@cgallarno , Yes I've given that a try. We never step into the IF statement even when the editor gets instantiated. We do however have the froalaOptions working.
`        $scope.froalaOptions = {
            toolbarButtons: ['fullscreen', 'bold', 'italic', 'underline', 'strikeThrough', 'subscript', 'superscript', 'fontFamily', 'fontSize', '|', 'color', 'inlineStyle', 'paragraphStyle', '|', 'paragraphFormat', 'align', 'formatOL', 'formatUL', 'outdent', 'indent', 'quote', '|', 'insertHR', '-', 'insertLink', 'insertImage', 'insertVideo', 'insertFile', 'insertTable', '|', 'undo', 'redo', 'clearFormatting', 'selectAll', 'html'],
            heightMin: 400

        }`
`
        var unwatch = $scope.$watch('froalaOptions', function (nv, ov) {
            if (nv.hasOwnProperty('froalaEditor')) {
                unwatch(); //De-register the watcher
                nv.froalaEditor('events.focus');
                
            }
        });``
