### ISSUE TITLE
Gulp build is not showing toolbar buttons

### ISSUE THREAD

**Issue by ankool** [froala/angular-froala#83]
My angular-froala editor is running well in my angularJS app but the gulp build (minified/uglified version) is not showing toolbar images in my editor. The editor shortcuts work so editor is loaded but image of each toolbar button is just blank. Do we need to make some exception in gulp build file to run froala editor for minfied builds or do we need some manual copy of image files after build to show them ?

**Comment by cgallarno** [comment]
The icons on the editor are actually font awesome font icons, not images. So you need to make sure that font awesome is available to your project after you've minified. @stefanneculai please elaborate if you have further information / instructions.

**Comment by stefanneculai** [comment]
I believe you're right, Cameron. The icons in the toolbar require font awesome to display by default. If you don't want to use Font Awesome, you could change them as explained here: https://www.froala.com/wysiwyg-editor/docs/concepts/custom-icon
