### ISSUE TITLE
Full screen editor in modal dialog no longer displays properly.

### ISSUE THREAD

**Issue by Veloxio** [froala/angular-froala#84]
Full screen mode seems to be broken in the newest verson, (the editor disappears from the modal overly and is no longer full screen). From what I can see, the old version (v2.0.5) spawns <div class="fr-modal fr-desktop"> in the root of the body, whereas the new version is using the original div located in a bootstrap modal dialog). The change could be causing the problem.

[Example](http://plnkr.co/edit/wizhU6uDT1O8eOMLkSqL?p=preview)

Also, there's no scroll bar in fullscreen mode, adding `.fr-fullscreen .fr-wrapper { overflow-y: auto;}` fixes the issue of not having a scroll-bar in full screen mode.

**Comment by stefanneculai** [comment]
This is an issue with the editor itself, not the Angular plugin. I created a new issue on the editor repo and I am closing this one.

**Comment by stefanneculai** [comment]
@Veloxio see https://github.com/froala/wysiwyg-editor/issues/1108#issuecomment-193823555.
