### ISSUE TITLE
Code view doesn't update the HTML.

### ISSUE THREAD

**Issue by Veloxio** [froala/angular-froala#85]
The code view does not update the HTML unless you click back to preview, potentially loosing the users changes.

[Example](https://www.froala.com/wysiwyg-editor/docs/examples/live-code-preview)

**Comment by stefanneculai** [comment]
Please see https://github.com/froala/angular-froala/issues/56#issuecomment-161735682. The editor is not syncing the content more often because if we'd do that the saved content might be bad formatted HTML.
