### ISSUE TITLE
difficulties in firing 'initialized' event

### ISSUE THREAD

**Issue by yanivlllev** [froala/angular-froala#86]
hey, i'm trying to figure out how to to implement froala's 'initialized' event in angular, but nothing works for me. what im trying to do is to make the TOOLBAR hidden until it's focused:

        $scope.froalaBottom = {
            toolbarInline: false,
            toolbarSticky: true,
            toolbarBottom: true,
            toolbarButtons: ['bold', 'italic', 'underline', 'strikeThrough', 'formatOL', 'formatUL'],
            events: {
                'froalaEditor.initialized': function (e, editor) {
                    editor.toolbar.hide();
                },
                'froalaEditor.focus': function (e, editor) {
                    editor.toolbar.show();
                },
                'froalaEditor.blur': function (e, editor) {
                    editor.toolbar.hide();
                }
            }
        };

what am i doing wrong?
thanks.

**Comment by cgallarno** [comment]
Hi @yanivlllev, My suspicion is that while the WYSIWYG is ready angular-froala is still booting. We'll have to look into whether or not we have this event called a more accurate time. But in the meantime, if you wrap your methods in a `$timeout` they'll work. Like this:

```javascript
events: {
     'froalaEditor.initialized': function (e, editor) {
          $timeout(function(){
               editor.toolbar.hide();
          });
     },
     'froalaEditor.focus': function (e, editor) {
          editor.toolbar.show();
     },
     'froalaEditor.blur': function (e, editor) {
          editor.toolbar.hide();
     }
}
```

**Comment by stefanneculai** [comment]
@yanivlllev I believe you're not using the latest version of the Angular plugin. Could you please check that?

**Comment by yanivlllev** [comment]
@stefanneculai hey, thanks for the reply.
versions: 
"angular":  "version": "1.4.9"
"angular-froala":   "version": "2.1.0"
"FroalaWysiwygEditor":  "version": "2.0.0-rc.1"

**Comment by stefanneculai** [comment]
Latest version for Angular plugin is 2.2.1. Editor version should be the same.
