### ISSUE TITLE
Does image upload callbacks work??

### ISSUE THREAD

**Issue by misawsneto** [froala/angular-froala#89]
Nice job with the angular integration... works well for me. 

I'm wondering if callbacks for the image upload work fine?

should i put he callbacks on $scope.froalaOptions?? 

`.froalaeditor({
        // Set the image upload parameter.
        imageUploadParam: 'image_param',

        // Set the image upload URL.
        imageUploadURL: '/upload_image',

        // Additional upload params.
        imageUploadParams: {id: 'my_editor'},

        // Set request type.
        imageUploadMethod: 'POST',

        // Set max image size to 5MB.
        imageMaxSize: 5 * 1024 * 1024,

        // Allow to upload PNG and JPG.
        imageAllowedTypes: ['jpeg', 'jpg', 'png']
      })
      .on('froalaEditor.image.beforeUpload', function (e, editor, images) {
        // Return false if you want to stop the image upload.
      })
      .on('froalaEditor.image.uploaded', function (e, editor, response) {
        // Image was uploaded to the server.
      })
      .on('froalaEditor.image.inserted', function (e, editor, $img, response) {
        // Image was inserted in the editor.
      })
      .on('froalaEditor.image.replaced', function (e, editor, $img, response) {
        // Image was replaced in the editor.
      })`

**Comment by cgallarno** [comment]
@misawsneto You do put the callbacks on the options object but like this:

```javascript
$scope.froalaOptions = {
     placeholderText: 'Add a Title',
     charCounterCount: false,
     toolbarInline: true,
     events: {
          'froalaEditor.initialized': function() {
               console.log('initialized');
          },
         'froalaEditor.image.beforeUpload': function (e, editor, images){
             //Your code 
         }
     }
};
```

**Comment by GZWZC** [comment]
@cgallarno Hello,this events is image.beforeUpload，and then upload events how we write?thx you
