### ISSUE TITLE
Model isn't updating after image uploading

### ISSUE THREAD

**Issue by kotmatpockuh** [froala/angular-froala#94]
When i upload some image to an empty wysiwyg-model: model isn't changing. It's changing only after i type something in wysiwyg.
In wysiwyg v1.* all was ok.

**Comment by kotmatpockuh** [comment]
Any plans to fix this issue, @stefanneculai?

**Comment by stefanneculai** [comment]
Just checked it on https://github.com/froala/angular-froala/blob/master/demo/index.html Sample 2 with the master version (V2.2.1) and works just fine. If you are using a custom way to upload the image, then you should push the changes into the undo stack so that the contentChanged event gets triggered.

**Comment by kotmatpockuh** [comment]
@stefanneculai 
maybe u have simple fiddle with angular+froala?
i'll show you

**Comment by stefanneculai** [comment]
@kotmatpockuh  Unfortunately, we don't have one. Looking forward for the jsFiddle.

**Comment by kotmatpockuh** [comment]
so, you haven't checked it with angular, right?

**Comment by stefanneculai** [comment]
We checked it with Angular locally, not in a jsFiddle using https://github.com/froala/angular-froala/blob/master/demo/index.html.

**Comment by kotmatpockuh** [comment]
something strange: i try it with plunker (not a localhost), and it doesn't work at all:

https://plnkr.co/edit/3Kh7saipkf3QPj1YRxZv?p=preview

$(...).froalaEditor is not a function(…)

why? core is defined in froalamain.js

**Comment by kotmatpockuh** [comment]
do you need exactly jsFiddle or .zip is good too?

**Comment by stefanneculai** [comment]
You have to include Angular after the editor JS, that's why that Plunker is not working.

**Comment by kotmatpockuh** [comment]
it's the same, then i got a lot of other issues: https://plnkr.co/edit/3Kh7saipkf3QPj1YRxZv?p=preview

**Comment by kotmatpockuh** [comment]
@stefanneculai  maybe U know other tool with npm support (to install packages via bower for example)

**Comment by stefanneculai** [comment]
https://plnkr.co/edit/gPF3x6T4z6tEu01hpKmN?p=preview

**Comment by kotmatpockuh** [comment]
finally i got it...

try to add ng-required directive to froala element: https://plnkr.co/edit/ki4aSx15I97OcE0yw2nh?p=preview

and add image to empty (without <p></p>) editor image:

http://i.imgur.com/73I98RU.png

**Comment by kotmatpockuh** [comment]
finally i got it...

try to add ng-required directive to froala element: https://plnkr.co/edit/ki4aSx15I97OcE0yw2nh?p=preview

and add image to empty (without <p></p>) editor image:

http://i.imgur.com/73I98RU.png

**Comment by kotmatpockuh** [comment]
finally i got it...

try to add ng-required directive to froala element: https://plnkr.co/edit/ki4aSx15I97OcE0yw2nh?p=preview

and add image to empty (without <p></p>) editor image:

http://i.imgur.com/73I98RU.png

**Comment by kotmatpockuh** [comment]
finally i got it...

try to add ng-required directive to froala element: https://plnkr.co/edit/ki4aSx15I97OcE0yw2nh?p=preview

and add image to empty (without <p></p>) editor image:

http://i.imgur.com/73I98RU.png

**Comment by stefanneculai** [comment]
@cgallarno could you take a look into this? It appears the methods are being called correctly, but the model isn't updated. Seems to the related to https://github.com/froala/angular-froala/pull/81, but that PR doesn't fix it.

**Comment by kotmatpockuh** [comment]
yeah!

and please reopen bug)

also, @cgallarno please make it ASAP - it's a critical issue...

**Comment by stefanneculai** [comment]
@kotmatpockuh please have patience. We're doing our best to fix this ASAP. It's not necessary to spam. Thank you.

**Comment by kotmatpockuh** [comment]
@stefanneculai man, it's github: i can write almost everything i want and when i want)
it's not your private task manager...

**Comment by cgallarno** [comment]
I believe the issue is caused  in angular-froala when ng-model checks to see if the model has any content, it does "dumb" check looking only for text. It's done this way to so empty p tags and lists etc, still fail validation since there's no actual content. We'll update it to support html elemets that are allowed to be empty.

**Comment by stefanneculai** [comment]
Are you referring to https://github.com/froala/angular-froala/blob/master/src/angular-froala.js#L105? Because it evaluates this as being `true`.

**Comment by cgallarno** [comment]
Nope, I'm on mobile so I can't verify but I think it's this check:

                ngModel.$isEmpty = function (value) {
                    var isEmpty = jQuery(jQuery.parseHTML(value)).text().trim().length <= 0;
                    return isEmpty;
                };

**Comment by stefanneculai** [comment]
Yes, that's it. I believe `ngModel.$isEmpty` should actually be removed because the editor does a check internally to see if it is empty and in case it's empty it returns an empty string.

**Comment by cgallarno** [comment]
Then we should update ngModel.$isEmpty to simply call froalas concept of
being empty. But we should keep it so angular can stay informed if it's
empty or not.
