### ISSUE TITLE
error "An invalid form control with name='' is not focusable"

### ISSUE THREAD

**Issue by yanivlllev** [froala/angular-froala#95]
hey, I keep getting this error when using a froala inside a `<form>`  with `required="required"` attribute:
> An invalid form control with name='' is not focusable. 

I don't have any other 'hidden' inputs/fields in my form, and when removing the `required="required"` attribute from the froala the console stops throwing the error. also, if i change the existing text in the froala - it also stops throwing the error.
not sure but i think it started after updating angular-froala and froala-wysiwyg-editor to v2.2.1

I need the required attribute to validate the form... any idea what's the issue?

this is the html:
`<textarea froala ng-model="project.description" required="required" autocomplete="off"></textarea>`

this is my config:
```
var buttons = ['bold', 'italic', 'underline', 'strikeThrough', 'formatOL', 'formatUL'];
angular.module('mean.theme')
    .constant('froalaConfig', {
        toolbarInline: false,
        toolbarButtons: buttons,
        toolbarButtonsMD: buttons,
        toolbarButtonsSM: buttons,
        toolbarButtonsXS: buttons,
        direction: 'ltr',
        linkAlwaysBlank: true,
        charCounterCount: false,
        key: '******************'
    });
```

update: 2 more things - 
1. when changing the froala's `<textarea>` element - in dev tools - from `display: none` to `display:block` - the form is valid again.
2. when changing the froala from `<textarea froala ng-model="project.description" required="required" autocomplete="off"></textarea>` to a `<div>` element instead `<textarea>` - the console doesn't throw the error anymore, but then it's not part of the form control/validation.

**Comment by stefanneculai** [comment]
Are you getting that in V2.2.3?

**Comment by yanivlllev** [comment]
it was on V 2.2.1 when i opened the issue. i'll update to the latest version and check if it still throws that error. thanks.

**Comment by stefanneculai** [comment]
Any news?

**Comment by stefanneculai** [comment]
I am closing this due to lack of response.

**Comment by leandroruel** [comment]
oh my god, got this problem today 2019.

**Comment by christophedebatz** [comment]
Same problem...
In fact, when I submit I'm gettiing this error but if, before submitting, I click on the "<>" to view de html code of the editor, then the submit works..
