### ISSUE TITLE
uploaded image is not saved when page is saved

### ISSUE THREAD

**Issue by cecilialam** [froala/angular-froala#96]
Hi, 
I am running into an issue with uploaded image. The image is uploaded and correct path is inserted to the editor. I inspect the element to confirm the image tag is inserted. However, when the page goes away, the image tag is not included in the html.
On the other hand, if I type after the uploaded image or go to the view code and back to the WYSIWYG, then the page goes away, the image tag will be included.

I tried doing the following and it does not help.

```
froalaEditor.image.loaded': function(e, editor, $img, response) {
                    editor.selection.save();
                    editor.events.trigger('save.force');
                }
```

Any suggestion how to work around it?

**Comment by stefanneculai** [comment]
You might be using an older version and the image was not saved in the undo stack. Please make sure you're using the latest version (2.2.1).

**Comment by cecilialam** [comment]
Thanks. I confirmed that v2.2.2 has fixed this issue.
