### ISSUE TITLE
Need help with correct auto-save init

### ISSUE THREAD

**Issue by mpmlj** [froala/angular-froala#99]
Hi,

**My case**
I'm building an article editing page. First - the page itself loads, and then its controller sends an ajax request to fetch an article. I initialize article attributes in the beginning of the controller with empty values, ex. vm.story.body, vm.story.headline, etc. and then my article loading call populates them.

**Problem**
1. If I initialize auto-save parameters (saveURL, saveParams, etc. etc.) during the froalaOptions init stage, it starts using empty values and never updates them after the article is loaded.
2. If I split vm.froalaOptions init into 2 stages, menu items - in the beginning of the controller (working fine), and auto-save params later, after the article-loading promise is resolved, then nothing happens - Froala won't run auto-save.

Please advise, what are my options to make Froala piking up updated field values OR initialize auto-save options only after I've loaded my content? Any other ideas are greatly appreciated!

Thank you,
Dennis

**Comment by cgallarno** [comment]
Hey @mpmlj, 

Have you looked at the possibility of using the manual init with the directive to only initialize the editor after you have your content? https://github.com/froala/angular-froala#manual-instantiation

**Comment by mpmlj** [comment]
@cgallarno 
Hi, thank you for the suggestion!
However, honestly, totally unclear how this should work (also I'm using John Papa's var vm = this; approach). I did check the demo, but still not clear and not docs in Internet regarding "froala-init".
I would really appreciate if you could provide an example that would be setting options, assigning a model with source data and manually initializing the editor.

Thank you!

**Comment by cgallarno** [comment]
If you clone this repository and run the demo, 'Sample 3' should show you everything you need.

**Comment by mpmlj** [comment]
@cgallarno 

Hi, thank you, I can initialize the editor separately on article load now, 
however an issue with autosave and updating saveParams in particular is still there:

1. On content load, I initialize froala's options like
`vm.froalaOptions.saveParams = {
                        body: vm.story.body,
                        deck: vm.story.deck,
...
}
`
2. For a model I'm using vm.story, i.e.
`<div froala="vm.froalaOptions" froala-init="initialize(initControls)" ng-model="vm.story.body"></div>`

3. When article's content changes, autosave is fired as expected, however saveParams are not updated. 
That's where I though manual init will help, but alas, the saveParams are note updated/empty.

Any thoughts are really appreciated!!
D.

**Comment by cgallarno** [comment]
If I'm not mistaken, $scope.title, and vm.story.title would be two different variables?

**Comment by mpmlj** [comment]
@cgallarno 
Hi, 
its a mistake in the example (sorry, my bad - I tried both options with $scope and with vm.), however not related to the issue: I can pickup a variable used as a model for the editor, however If I add other variables to saveParams - they are not updated and sent with their initial state.

**Comment by cgallarno** [comment]
So is it that the title variable isn't updating? is that froala model? You might want to look into setting `immediateAngularModelUpdate` to true. https://github.com/froala/angular-froala#directive-specific-option

By Default the model doesn't update instantly it waits for froala contentUpdated event for performance, this option updates the model on every keystroke.

**Comment by mpmlj** [comment]
@cgallarno 
>> So is it that the title variable isn't updating? is that froala model? 
No, model value for the Froala editor is being sent w/o problems. I've sorted this out.
What I mean is that you can add other variables/models to saveParams, and they are not getting updated.

**Comment by cgallarno** [comment]
Could you provide more of your controller code, or replicate this in a jsfiddle?

**Comment by mpmlj** [comment]
@cgallarno 
Hi, I've put together a gist here: https://gist.github.com/mpmlj/7a0e46faf5b99e3c3d1acd99930b5ca4
Sorry, the controller itself is pretty huge so can neither put it here or reproduce via jsfiddle.
Hope this helps!

Thank you
D

**Comment by cgallarno** [comment]
Hey @mpmlj good news, you're not crazy! haha. I replicated the issue using the angular-froala demo. My first thought is that the froala editor is just taking the value of those variables when it's initialized, and not creating a pointer to the variable itself. @stefanneculai is that correct?

I Haven't tested the original froala editor yet to see if this issue stems from there or not.

**Comment by stefanneculai** [comment]
Indeed if values are changed after the editor is initialized, they won't reflect that in the editor. What you should do is to change the editor option too: https://github.com/froala/wysiwyg-editor/issues/778#issuecomment-142609365

**Comment by cgallarno** [comment]
@stefanneculai Thanks for the clarification, so @mpmlj all you need to do is to reassign that option in your save.before event

```js
events: {
     'froalaEditor.save.before': function(e, editor){
          editor.opts.saveParams.title = vm.story.title
     }
}
```

**Comment by mpmlj** [comment]
@cgallarno 
Aha, "editor.opts" did the magic!
I tried 2 days before without success doing 
`vm.froalaOptions.saveParams.headline = vm.story.headline;`

Thank you, guys!
